<?PHP

if ($number == "") { $number = mt_rand (0,559); }
else if ($show == 1) { $number = $number; }
else { $number -= 1; }

if ($size == "") { $size = 3; }

$duoEnglish = array(
"1. We must respect the will of the individual.",
"2. Take it easy. I can assure you that everything will turn out fine.",
"3. Let go of your negative outlook on life. Always maintain a positive attitude.",
"4. You should be fair to everyone regardless of national origin, gender, or creed.",
"5. Equality is guaranteed by the Constitution.",
"6. He leaned against the pillar and gazed at the Statue of Liberty.",
"7. A woman passed by me giving off a subtle scent of perfume. It reminded me of my ex-girlfriend.",
"8. 'Natto' smells awful but tastes terrific.",
"9. 'I'm soaked with sweat.' 'Stand back! You stink. Take a shower.'",
"10. Bob was so beside himself that he could scarcely tell fact from fiction.",
"11. His new novel, which combines prose with his gift for poetry, is going to be published.",
"12. An up-to-date edition of the encyclopedia will come out next month.",
"13. Ms. Yamada translated the fascinating fairy tale into plain Japanese.",
"14. The following passage is quoted from a well-known fable.",
"15. 'Are you familiar with contemporary literature?' 'I know next to nothing about it.'",
"16. At times I confuse 'curve' with 'carve'.",
"17. Don't be shy. Your pronunciation is more or less correct.",
"18. This article contains tips for those who are eager to increase their vocabulary.",
"19. His latest works are on display at the city hall. They are fabulous beyond description.",
"20. 'Could you move over a little?' 'Oh, sorry. I didn't realize I was taking up so much space.'",
"21. 'What's this ugly object?' 'This is a piece of abstract art!'",
"22. I begged Richie to lend me a hundred bucks, but he shook his head, saying, 'I'm broke, too.'",
"23. 'I'm apt to buy things on impulse whenever something is on sale.' 'So am I.'",
"24. As it is, ordinary people cannot afford to purchase such luxuries.",
"25. As we anticipated, the unemployment rate has risen three quarters in a row.",
"26. I have to cut down on my expenses, so from now on, I'm going to keep track of them on a daily basis.",
"27. In any case, the union has to compromise to a certain extent.",
"28. Competent mechanics are in great demand, so they earn decent wages.",
"29. The president announced a concrete plan to carry out welfare reform.",
"30. His policy will no doubt lead to dismal consequences. It needs a thorough review.",
"31. It goes without saying that the aging of society is inevitable.",
"32. Please take a look at this chart. It indicates that juvenile delinquency is on the increase at an alarming rate.",
"33. In many business districts, there are a lot of vacant lots which have been for sale for years.",
"34. The population density in the metropolis is gradually decreasing.",
"35. In all likelihood, the birthrate will continue to decline steadily for years to come.",
"36. The power plant supplies the remote county with electricity.",
"37. You are not allowed to operate this device without permission.",
"38. In fact, the inhabitants have been exposed to radiation.",
"39. One cannot emphasize too much the potential danger of nuclear energy.",
"40. For years the press overlooked the problem. But now, if anything, they are making too much of it.",
"41. As well as cultivating grain, the farmer runs a grocery store.",
"42. The research institute was established in the late 1960s.",
"43. Why don't you consult Starr in person? He's by far the most prominent attorney around here.",
"44. I'll write it down just in case, because I have a bad memory.",
"45. The lawyer recommended that his client take legal action against the insurance company.",
"46. They are entitled to be compensated for their injuries.",
"47. So far, no less than 200 people have died of the flu epidemic.",
"48. The effect of those pills is intense but brief.",
"49. He has a habit of biting his nails. It's absolutely disgusting.",
"50. My grandma strained her back when she bent down to hug my son.",
"51. If you have a stiff neck, try an herbal remedy.",
"52. Medical breakthroughs have brought about great benefits for humanity as a whole.",
"53. We can't apply cloning techniques to cattle, let alone human beings. It's forbidden.",
"54. Whales are classified as mammals.",
"55. The theory of evolution is beyond the reach of my imagination.",
"56. The biologist is proud of his historic discovery and doesn't mind boasting about it.",
"57. On ethical grounds, they are opposed to so-called gene therapy.",
"58. The initial symptoms of the disease are fever and a sore throat.",
"59. The structure of the brain is complex.",
"60. Owing to illness, some representatives were absent from the annual conference.",
"61. Little by little, my son-in-law is recovering from stomach cancer, and now he is in good spirits.",
"62. 'This is fake, isn't it?' 'Hey, it's genuine antique.' 'No way!'",
"63. 'Anything else?' 'That's it.' 'For here or to go?' 'To go.'",
"64. 'How much is this rug?' '$100 including tax.' 'OK, I'll take it.'",
"65. I don't think those pants look good on you. Try these on. They're really in now!",
"66. He got out of the cab in haste, saying, 'Keep the change.'",
"67. Delivery service is available to our customers for a slight extra charge.",
"68. 'It's on me.' 'No. You treat me every time we eat out.' 'Well, okay. Let's split the check then.'",
"69. While I was hanging out at the mall, I ran into Ken.",
"70. I was short of cash, so I withdrew the $100 that I had deposited in my bank account last week.",
"71. On her way home she was robbed of her purse.",
"72. 'That's odd! Tell me how it happened.' 'I'll explain it to you later.'",
"73. My parents gave me a 6 p.m. curfew as a punishment because I broke my promise.",
"74. As the proverb goes, 'The end justifies the means.'",
"75. Now that I've found that there's no one to turn to, I'll have to stand on my own two feet.",
"76. The chairman cut me off, saying, 'Time to wind things up. Let's take a vote.'",
"77. We exchanged frank opinions in the meeting, but consensus is yet to be reached regarding this matter.",
"78. 'Do you agree or disagree with him?' 'I'm on his side.'",
"79. Strictly speaking, his view differs somewhat from mine.",
"80. Could you go over it again? I couldn't make out what you were getting at.",
"81. No one backed me up at first, but eventually I talked everyone into going along with my plan.",
"82. 'I admire your perseverance, courage and wisdom.' 'You flatter me!'",
"83. In making a decision, I rely not on logic but on instinct.",
"84. He came up with an ingenious, sensible solution and immediately put it into practice.",
"85. From an objective viewpoint, the former is inferior to the latter.",
"86. Your idea sounds marvelous in theory, yet I don't think it will work in practice.",
"87. We expected him to defeat his opponent, but he failed to live up to our expectations.",
"88. Ironically, despite their best endeavors, their mission resulted in complete failure.",
"89. Her genius makes up for her lack of firsthand experience.",
"90. She possesses a great capacity for overcoming any obstacle.",
"91. Without your solid support, the deal would have fallen through. I'm grateful to you.",
"92. Bringing flammable items into the cabin is prohibited.",
"93. Our flight to Vienna was delayed on account of a minor accident.",
"94. The plane blew up and plunged into the ocean, killing all the people on board.",
"95. They are working around the clock looking into the cause of the crash.",
"96. Unfortunately, few passengers survived the catastrophe.",
"97. The aviation expert analyzed the statistics in detail.",
"98. On behalf of all the staff, I'd like to express our sympathy for the victims.",
"99. In a sense, he is to blame for the disaster.",
"100. The vehicles are inspected for defects every three months.",
"101. I was amazed to see that our utility bills came to so much!",
"102. 'Turn the faucet off!' mom yelled in a rage.",
"103. Tighten the lid so the food doesn't go bad.",
"104. 'Can I borrow your scissors?' 'Sure, here you are.'",
"105. You can substitute some transparent glue for a needle and thread.",
"106. I dyed this fabric and it shrank.",
"107. I'm getting rid of this leather jacket because it's worn out at the elbows.",
"108. Add some flour to the mixture and stir it until it becomes thick.",
"109. 'What should we do with the leftovers?' 'Keep them in the fridge for now. I'll heat them in the microwave later.'",
"110. I could have laid out all that money on a new PC, but on second thought I decided to put some aside for a rainy day.",
"111. A cell phone has become something of a necessity, and I can't do without one.",
"112. No sooner had I sat back and relaxed than my wife asked me to do the chores.",
"113. She laid the baby down and lay beside him.",
"114. Put this stuff away! It's in the way.",
"115. When the kids made believe they were dinosaurs, they were scolded by their mother.",
"116. After he bumped into the shelf, the priceless china fell and shattered into fragments.",
"117. 'Can you keep an eye on my kids for a while? I need to pick up Ken.' 'No problem.'",
"118. Our neighbor told us off for making a mess in his yard.",
"119. Dolly resembles her big sister in every way. You can't tell them apart.",
"120. As a rule, twins have a lot in common.",
"121. I'm tired of doing the dishes, doing the laundry, and so on!",
"122. My favorite pastime is strolling along the shore. It's pleasant.",
"123. 'I'm exhausted! Let's take a break in the shade.' 'Why not?'",
"124. 'Bob, this vending machine is out of order.' 'Oh no! I'm dying of thirst!'",
"125. He fainted with hunger and fatigue, but came to after a while.",
"126. The auditorium was empty except for a single piece of furniture.",
"127. Any apartment will do as long as the rent is low. I'm not particular about it.",
"128. His sixty-year-old cousin inherited a piece of real estate by a lake.",
"129. So much for small talk. Let's get down to business.",
"130. Lucy resented the aggressive salesman trying to make her sign the contract.",
"131. There are a number of factors discouraging us from investing in stocks.",
"132. Japan imports various raw materials and exports manufactured goods.",
"133. In the course of its economic development, Japan has abandoned its traditional values.",
"134. The world is faced with an unprecedented crisis.",
"135. In short, the purpose of the regulations is to protect domestic industries.",
"136. In order to keep up its competitiveness in the world, Japan must undertake sweeping deregulation in earnest.",
"137. We cannot turn our backs on desperate people who are at risk.",
"138. The parliament decided to provide developing countries with financial aid.",
"139. Some say the British monarchy should be abolished. What do you think?",
"140. They sought shelter from the attack but found no place to hide.",
"141. There's little prospect that the two countries will make significant progress in disarmament.",
"142. The negotiations are under way. Before long, they will enter a crucial phase.",
"143. The slaves were anxious to alter their destinies.",
"144. The aristocrats abused their privileges to their hearts' content.",
"145. The revolution in itself bore no fruit, after all.",
"146. Bob cut in on our conversation, saying, 'I'm against it!' But everybody ignored him.",
"147. We skipped his turn on purpose.",
"148. He saw someone being bullied, but he turned a blind eye.",
"149. When Nick and I cheated on an exam, I was suspended from school. As for Nick, he got away with it.",
"150. They are hostile to Richard because they are jealous of his wealth and status.",
"151. I hate him! He behaves as if he were somebody.",
"152. In spite of our compliments, he frowned and turned away. He was so rude!",
"153. He claimed that the enormous property was at his disposal.",
"154. The more stubborn you are, the more isolated you become.",
"155. 'Don't beat around the bush! What am I supposed to do?' 'Just wait and see. Time will tell.'",
"156. Please hand in your assignment via e-mail no later than 5:00 P.M. on June 10.",
"157. Joe is anything but diligent. That's why he flunked math again.",
"158. His thesis doesn't make sense. To begin with, its theme is obscure.",
"159. His essay was concise and to the point.",
"160. 'How are you going to deal with this complicated problem?' 'Leave it to me! It's a piece of cake.'",
"161. 'Nick, I want you to look this over before I turn it in.' 'Sorry, but I have my hands full right now.'",
"162. 'What if I don't meet the deadline?' 'I bet he'll get mad at you!'",
"163. Your summary leaves nothing to be desired apart from the terrible handwriting.",
"164. You ought to think over whether the premise is valid or not.",
"165. Above all, scientific terms call for precise definitions.",
"166. First of all, learn the formula by heart.",
"167. To calculate the volume, multiply the length by the width by the depth.",
"168. Tiny cracks were found in the bottom of the barrel.",
"169. This chapter will focus on the concepts of geometry.",
"170. Phil is much more interested in academic subjects than in practical skills.",
"171. 'Something's gone wrong with this microscope. I need to have it repaired.' 'Let me see it. Maybe I can fix it.'",
"172. 'What is an 'instrument'?' 'For instance, a gauge, such as a thermometer or a barometer.'",
"173. The minute particles are barely visible to the naked eye.",
"174. Muscle tissue consists of a vast number of cells.",
"175. This substance is mostly composed of hydrogen and oxygen.",
"176. The exact temperature is 22.68 degrees Celsius.",
"177. 'Naomi likes to show off her perfect figure. I wish I were thin like her. I envy her.' 'You could go on a diet.'",
"178. I fell in love with Naomi first sight. Three months later, I took a chance and proposed to her, but she turned me down.",
"179. I met the man by chance. He's gentle and smart. What's more, he's single!",
"180. His nephew was brought up to be modest and considerate.",
"181. I introduced Bob to my folks, and they took to him at once.",
"182. People should be judged not so much by how they look as by who they are.",
"183. 'It's not your title that counts. That's for sure!' exclaimed Bob.",
"184. As a self-made man put it, 'A man of vision will make good in the end.'",
"185. Keep in mind that youth is not eternal.",
"186. I can't figure out why on earth everybody feels so much contempt for Bob!",
"187. I can't help laughing at him because he keeps on making stupid mistakes. He'd be the last person to learn his lesson.",
"188. To make matters worse, he isn't even conscious of annoying us.",
"189. Since I was in a hurry, I put my gloves on inside out by mistake.",
"190. Dave is fat and clumsy. When he leaped over the shallow stream, he stumbled and twisted his ankle.",
"191. 'I'm scared of heights.' 'You're a coward!'",
"192. The passive man seldom, if ever, expresses himself in public.",
"193. Nick convinced me that all superstitions are irrational.",
"194. I tremble with fear at the thought of an injection.",
"195. Since Bob is lazy at heart, he frequently neglects his duties.",
"196. While Bob was at work, Jennifer was at home absorbed in silly soap operas.",
"197. Bob likes cartoons, but I don't think much of them. As a matter of fact, they're boring.",
"198. It occurred to me that he was holding something back, because he wouldn't look me in the eye.",
"199. When her patience gave out, she grabbed his collar and swore at him.",
"200. I must admit we quarrel every now and then, but generally we're on good terms with each other.",
"201. 'Do you mind if I stop by your house?' 'No, not at all. Be my guest!'",
"202. Hold on. I'll be right back. Don't hang up!",
"203. I can't put you up. For one thing, my dad drops in on me from time to time.",
"204. While Jennifer was standing still, Bob was pacing back and forth along the sidewalk.",
"205. 'Let's make up, Lisa.' 'Stop taking me for granted! We're through for good this time. I mean it!'",
"206. Come on! Don't get so emotional, Lisa. I didn't mean to hurt you. Let's talk it over.",
"207. 'You betrayed me!' 'Please forgive me. How can I make it up to you?' 'I'll get even!'",
"208. You should confess your sins rather than conceal them.",
"209. Keep your word; otherwise you'll end up losing face.",
"210. Bob sticks to his moral principles and believes that honesty pays off in the long run.",
"211. 'Cheer up! You couldn't help it.' 'I did my best.' 'I know. Don't dwell on the past. You can start over!'",
"212. 'Jane, please do me a favor and give me a ride to Times Square.' 'I wish I could, but I'm tied up right now.'",
"213. As usual, Mike turned up on time. He's very punctual.",
"214. The other day I ran out of gas in the middle of a busy Interstate.",
"215. A truck driving ahead of me skidded, turned over, and scattered its load all over the road.",
"216. He recalled that a collision had been avoided by sheer luck.",
"217. In case of an emergency, get in touch with my agent right away.",
"218. 'Jane, where are you heading?' 'I think we're lost. We went in the wrong direction.' 'Damn! Pull over!'",
"219. My rusty Ford broke down, obstructing the intersection.",
"220. There are so many fine scratches and dents on its surface, it's no use polishing it.",
"221. 'Hey, we're stuck in a traffic jam!' 'Chill out, Joe. Let's take a shortcut! We'll get there in time.'",
"222. 'I've got a flat tire. Can you give me a hand?' 'I'd be glad to.'",
"223. The ambulance went out of control and came close to running over a pedestrian.",
"224. He contends that primitive life once existed on Mars.",
"225. The crew is busy preparing for the voyage into outer space.",
"226. They conducted a series of experiments under zero gravity.",
"227. Many astronomers assure that the universe will expand infinitely.",
"228. The astronauts were greeted with spontaneous applause.",
"229. A fund was set up with a view to preserving our endangered planet.",
"230. The massive flood paralyzed the local transportation network.",
"231. The equator divides the globe into two hemispheres.",
"232. I think it's cruel to trap animals for fur coats.",
"233. The organization plays a principal role in wildlife conservation.",
"234. Many fragile species are on the verge of extinction.",
"235. The prolonged drought did severe damage to the crops.",
"236. Tropical rain forests are quickly disappearing on a global scale. In part, it's due to acid rain.",
"237. It is said that global warming is directly related to carbon dioxide emissions.",
"238. The destruction of the ozone layer affects the environment.",
"239. The committee called on all nations to work side by side to curb air pollution.",
"240. A satellite was launched into orbit to monitor melting glaciers.",
"241. The ecologist has warned us time and again that petroleum is not only a blessing but also a curse.",
"242. The continent is abundant in fossil fuels.",
"243. The region is relatively rich in mineral resources.",
"244. Wheat accounts for approximately two-thirds of agricultural production in the area.",
"245. Fertile soil is indispensable for a good harvest.",
"246. A humid climate is characteristic of the peninsula.",
"247. The active volcano erupts at regular intervals.",
"248. The Panama Canal connects the Atlantic with the Pacific.",
"249. The geographical features here are similar to those of our prefecture.",
"250. More often than not, famine is accompanied by plague.",
"251. A devastating earthquake hit the state capital, leaving tens of thousands of residents homeless.",
"252. 'Watch out! The ceiling is giving way!'",
"253. The weather forecast says the typhoon is likely to accelerate and approach the coast.",
"254. 'It's still up in the air whether the game will be called off or not.' 'So what? It makes no difference to me.'",
"255. 'It's foggy, isn't it?' 'It sure is. But chances are it'll clear up later on.'",
"256. For the most part, modernization is identified with westernization.",
"257. Urban culture appears to be attractive to many people, in particular, to younger people.",
"258. 'AI' stands for 'artificial intelligence.'",
"259. Household appliances are becoming more convenient day by day.",
"260. My income is not adequate to provide for my family of four, but we have to make the best of it.",
"261. The popularity of a website depends on its content.",
"262. You've got to keep up with it. Once you fall behind, it's hard to catch up.",
"263. As technology rapidly advances, it's tough to keep pace with it.",
"264. More and more people are rushing to make use of the interactive nature of the medium.",
"265. Innovation has something to do with the ability to notice unusual phenomena.",
"266. A bunch of other companies are imitating our excellent methods.",
"267. The once desolate valley was transformed into a thriving hub of hi-tech business.",
"268. Although there's still plenty of room for improvement, his invention is superior to conventional equipment in every respect.",
"269. The strength of the firm is attributed to its unique and future-oriented strategies.",
"270. SONY has integrated a wide range of functions into this cool gadget. It's catching on from coast to coast.",
"271. This tool comes in handy, so I always keep it close at hand.",
"272. 'In general, consumers prefer quantity to quality.' 'It's the other way around today.'",
"273. Obviously, the advertisement is aimed at teenagers.",
"274. The factory now under construction will assemble 1,000 VCR units per day.",
"275. Efficient machinery replaced manual labor.",
"276. In those days, the gigantic corporation had a virtual monopoly over internal commerce.",
"277. With restrictions removed, thousands of new enterprises have come into being.",
"278. As a result of his ridiculous venture, he is in danger of going bankrupt.",
"279. Compared to the previous year, business is looking up in terms of sales. However, we haven't made any profit yet.",
"280. 'I'm going to be transferred to an overseas branch.' 'Oh, I'll miss you. Please drop me a line.'",
"281. While he was away on business, his wife gave birth to a baby boy.",
"282. Apparently, Nick wasn't willing to take on the task because it would just add to his burdens.",
"283. Bob had intended to take her out tonight, but he had to work overtime.",
"284. 'Please estimate the losses by Friday at the latest.' 'I'll manage it somehow.'",
"285. 'Nick, I'm counting on you.' 'OK, I'll see to it.' 'Thanks, I appreciate it.' 'Don't mention it.'",
"286. He pretends to be enthusiastic when his boss is around.",
"287. He got promoted at the expense of his colleagues. He should be ashamed of himself.",
"288. As the recession set in, temporary employees were laid off one after another.",
"289. Nowadays, many people are out of work against their will. Who is responsible for that?",
"290. I've gotten pessimistic, and I'm worried about something I would never have been concerned about before.",
"291. Today, even white-collar workers are confronted with great hardships.",
"292. The authorities are striving in vain to stabilize the currency.",
"293. We've come to the conclusion that nothing is more urgent than reducing Japan's huge deficit.",
"294. The questionnaires were distributed at random.",
"295. All you have to do is fill in the blanks below. (Please print in black or blue ink.)",
"296. In addition to a 10% discount, you can pick out an optional excursion for free.",
"297. Round-trip fares to each destination are as follows.",
"298. 'Don't forget to confirm your reservation in advance.' 'I won't.'",
"299. Be sure to check in at least 45 minutes prior to departure time.",
"300. I attached my nametag to my baggage, but it soon came off.",
"301. On average, these packages weigh two pounds.",
"302. This plastic garbage bag is free of hazardous chemicals.",
"303. This flashlight is getting dim. It needs new batteries.",
"304. Excuse me. How often do the shuttle buses run to downtown New York?",
"305. The motel can accommodate as many as 400 guests.",
"306. This suite is three times larger than my condominium.",
"307. Littering in this facility is subject to a maximum fine of $500.",
"308. That restaurant is always packed. We'd better make a reservation beforehand.",
"309. 'Sorry to interrupt your meal but I'd like a word with you in private.' 'Can I get back to you later?'",
"310. The cook was astonished at his incredible appetite.",
"311. 'What's going on down there? I'm curious.' 'I have no idea.'",
"312. Excited fans were hanging around the rear exit hoping to catch a glimpse of Michael.",
"313. On encountering the celebrity, they asked for his autograph.",
"314. Whenever I go abroad, I suffer from jet lag and diarrhea.",
"315. 'I feel sort of dizzy and I feel like throwing up.' 'You look pale!'",
"316. Take some aspirin. It will cure you of your headache in no time.",
"317. 'I'm afraid I'm coming down with something.' 'You should take a day off.'",
"318. Some of the ingredients in this beverage are harmful, especially if you are pregnant.",
"319. Good nutrition is vital for an infant's growth.",
"320. Moderate exercise stimulates the circulation of the blood.",
"321. My physician advised me to refrain from alcohol for the time being.",
"322. I do want to get into shape and lose some weight, so I go swimming every morning.",
"323. He caught a nasty cold because he stayed up late last night.",
"324. The surgeon persuaded him to undergo an organ transplant.",
"325. Since our father is bedridden, we take turns looking after him.",
"326. Our hypothesis is that eating excessive amounts of junk food contributes to early mortality.",
"327. The government did not take appropriate measures to prevent the infection from spreading.",
"328. The minister was obliged to resign from the Cabinet.",
"329. Many people regard the current compulsory education system as being obsolete.",
"330. Many people encouraged me to fulfill my ambitions.",
"331. To make his dreams come true, he dropped out of school and made his way to Tokyo.",
"332. 'What do you do?' 'I'm a college student, a freshman at Harvard.' 'What's your major?' 'Philosophy.'",
"333. Tuition will be raised by nearly ten percent as of April 1, 2001.",
"334. 'I'm of two minds whether to apply for the scholarship or not.' 'Give it a try!'",
"335. As soon as he graduated from Keio University, he took over his family's business.",
"336. You aren't cut out for the military because of its rigid discipline.",
"337. I am determined to make a living as a playwright at all costs.",
"338. As he grew up, he learned to put things in perspective.",
"339. Conformity is an essential element of our homogeneous community.",
"340. I'd rather go my own way than toil away for a company. Trying to fit into a mold gets me nowhere!",
"341. Tom takes after his uncle in personality. I mean, he is obstinate by nature. He never gives in.",
"342. When the time is ripe, be bold and go for it! I'll stand by you.",
"343. I'll stand up for what I believe in and won't yield to any threats.",
"344. 'If only I could conquer my weaknesses!' 'It's up to you.'",
"345. You should make the most of this rare opportunity to demonstrate your talent.",
"346. You won't let me down. I have great faith in you. You can make it!",
"347. The spectators were moved by her graceful performance.",
"348. In 1995, Ando received architecture's most prestigious award.",
"349. In the face of adversity, Mike accomplished an extraordinary feat. He deserves praise.",
"350. The audience was impressed by his eloquent lecture.",
"351. From a humble background, John achieved worldwide fame.",
"352. He accumulated a tremendous fortune during the postwar era.",
"353. He used to be well off and generous, but now he lives from hand to mouth.",
"354. Nick is by no means satisfied with the reward. He is selfish and greedy.",
"355. 'You owe me $200 altogether, Bob. When are you going to pay me back?' 'I'm sorry. I'm hard up.' 'There you go again!'",
"356. To Brian's surprise, his debt amounted to a considerable sum.",
"357. Stop clinging to your glory days, or you'll be left behind.",
"358. You cannot escape from today's harsh realities, so you must adapt to them.",
"359. Prosperity does not last forever. In other words, it will come to an end one of these days.",
"360. Proper qualifications are required for the position; computer literacy is a must.",
"361. Enclose your resume in this envelope and submit it to the personnel department.",
"362. It's optimistic of you to believe that things will work out. At best there's a fifty-fifty chance.",
"363. Registration forms can be obtained free of charge.",
"364. Please give us a call now if you want to participate in the workshop!",
"365. For further inquiries, please feel free to contact us toll-free at 1-800-555-1212.",
"366. 'How's it going, Bob?' 'Couldn't be better! I did well in my job interview!' 'Good for you!'",
"367. He gave instructions to the trainees, but they couldn't make heads or tails of them.",
"368. You can't do two things at one time! It's out of the question. Do them one by one.",
"369. 'Bob, don't disturb her. Mind your own business,' he whispered.",
"370. If you persist in bothering her like that, she'll lose her temper.",
"371. He was so childish that he couldn't resist temptation.",
"372. 'Stop making a fuss. It really gets on my nerves!' she shouted.",
"373. There's no point in talking back to Nick. He is a 'dictator,' so to speak.",
"374. They are very polite in his presence, but actually, they always talk about him behind his back.",
"375. 'You despise Nick, don't you?' 'On the contrary! I look up to him.'",
"376. His constant insults aroused her anger.",
"377. I'm fed up with just shuffling papers and pouring coffee. I've make up my mind to quit!",
"378. In reality, many people have difficulty making ends meet. How can you get by on 100,000 yen a month?",
"379. Female clerks may well complain about their routines, which are not challenging at all.",
"380. Thanks to a fundamental restructuring, our surplus has swelled threefold.",
"381. Many people today think of loyalty to a company as an absurd notion.",
"382. I have to commute all the way from a distant suburb. I'm sick of it!",
"383. I want to spend the rest of my life pursuing my ideals.",
"384. After retirement, Teresa devoted herself to caring for orphans.",
"385. For the sake of children in need, we cooperated to collect donations.",
"386. The charity is named after a man who gave away some two billion yen.",
"387. His autobiography was released today and was sold out by noon.",
"388. Ted, who is often referred to as a man of integrity, is going to run for mayor.",
"389. The candidate was disappointed by the outcome of the election.",
"390. The municipal council should concentrate more on specific issues.",
"391. It is the case that those who live on a pension are forced to lead a hard life.",
"392. We should leave out this data. It's far from accurate.",
"393. We tend to associate politicians with hypocrisy.",
"394. They are primarily concerned with exploiting us, not with enhancing our living standards.",
"395. The man once exerted a dominant influence on the conservative party, but now his power is diminishing.",
"396. The spokesperson refused to make any comment, saying, 'It's under investigation.'",
"397. The police say there's someone pulling strings behind the scenes.",
"398. The executives entertained the bureaucrats at ryotei, or exclusive Japanese restaurants, hoping for something in return.",
"399. His secretary flatly denied leaking any confidential information.",
"400. No one dares to contradict his/her employer for fear of being fired.",
"401. He sacrificed his promising career to retain his dignity.",
"402. I might as well kill myself as reconcile myself to my fate.",
"403. He was about to commit suicide by swallowing poison when he thought better of it.",
"404. The vague rumor proved to be false. Nevertheless, some skepticism lingers on.",
"405. A senior official is suspected of accepting bribes from a company, but there isn't sufficient evidence to arrest him.",
"406. Jason, who was in charge of the project, was dismissed for corruption.",
"407. To my knowledge, he has not been involved in the fraud scheme.",
"408. They found out the truth while examining a pile of relevant documents.",
"409. During the trial it came to light that they had been covering up illegal transactions for decades.",
"410. The detective took down his testimony on the spot, word for word.",
"411. For the first time in my life, I felt a pang of conscience, but there was no other way out.",
"412. I'm still haunted by a vivid nightmare I had last night.",
"413. By and large, reporters don't hesitate to intrude on one's privacy.",
"414. The author revised his manuscript over and over again.",
"415. He is second to none when it comes to finding fault with others.",
"416. On the whole, the elite are not sensitive to criticism.",
"417. When a tabloid revealed that he was a drug addict, his reputation was all but ruined.",
"418. They considered every aspect of the defense program and pointed out numerous flaws.",
"419. We will not tolerate anyone who engages in terrorism.",
"420. The notorious rebel was ultimately captured and confined to jail.",
"421. Troops were swiftly called in to put down the riot.",
"422. We should appeal to reason instead of resorting to violence.",
"423. I suggest we adopt flexible tactics for the moment.",
"424. The armed forces succeeded in occupying the entire territory.",
"425. Under the circumstances, the enemy has no choice but to surrender. They can't hold out any longer.",
"426. Sooner or later, the hostages will be set free.",
"427. Under the reign of tyranny, innocent people were deprived of their citizenship.",
"428. Some soldiers were reluctant to obey the commands.",
"429. His regime is bound to collapse.",
"430. The allies condemned the invasion as a violation of UN resolutions.",
"431. We cannot rule out the possibility that civil war will break out in that country.",
"432. The colony declared independence and became a republic.",
"433. An immense monument was erected in honor of the noble patriot.",
"434. He got down on his knees and prayed for the souls of the deceased.",
"435. The Supreme Court is located near the Imperial Palace.",
"436. The pro-choice group protested against a ban on abortion.",
"437. Senator Ford remained neutral in the bitter controversy.",
"438. Ford has been in a difficult situation all week long. He is no longer capable of coping with it.",
"439. The summit talks are to be broadcast simultaneously throughout the world.",
"440. Diplomatic dialogue helped put an end to the conflict.",
"441. Johnson was appointed as a goodwill ambassador to foster mutual understanding between the two nations.",
"442. The specialist predicts international tension will build up.",
"443. In my opinion, permanent peace is nothing but an illusion.",
"444. Ethnic minorities struggle against prejudice, poverty, and oppression.",
"445. We must make every effort to do away with all discrimination.",
"446. The immigrants have endured physical and mental pain.",
"447. The amendment was rejected because it didn't take racial diversity into account.",
"448. Needless to say, the refugees were longing for freedom.",
"449. According to a survey, three in five people today are indifferent to foreign affairs.",
"450. What will become of Janpan-U.S. relations if the security treaty expires?",
"451. Unless Japan eliminates its unfair tariffs, the U.S. will impose sanctions.",
"452. Trade friction might arise between the two nations at any moment.",
"453. Our top priority is to settle this dispute once and for all, so we are ready to meet them halfway.",
"454. The federal budget was narrowly approved by Congress.",
"455. He argues that the administration must look for alternative sources of revenue.",
"456. A poll shows that an overwhelming majority is in favor of the legislation.",
"457. The cops are searching for clues to the brutal murder.",
"458. The man must be insane. He can't distinguish vice from virtue.",
"459. The fingerprints left on the weapon correspond with the suspect's.",
"460. It took us all by surprise when the noted psychologist was accused of kidnapping.",
"461. The jury's guilty verdict gave rise to widespread debate.",
"462. The man pleaded for mercy, but he was sentenced to twenty years in prison for his crime.",
"463. The officer on duty perceived an elderly man coming up behind him.",
"464. He caught sight of a thief attempting to break into the house.",
"465. The day before yesterday he witnessed a weird incident in the wilderness.",
"466. I became aware of someone staring at me from across the aisle, so I turned around. But there was no one in sight.",
"467. She screamed with horror as someone took hold of her arm.",
"468. Informed of her safety, he breathed a sigh of relief.",
"469. The bullet penetrated his chest, leaving him in critical condition.",
"470. At present, it's still uncertain whether it was done deliberately or by accident.",
"471. A deli caught fire and burned down, leaving a heap of ashes.",
"472. All of a sudden the fireworks warehouse exploded, and it took two days to put out the blaze.",
"473. A bomb went off in a thirty-story building, and more than fifty people were seriously wounded.",
"474. A cargo vessel, bound for Athens, sank in the Mediterranean without a trace.",
"475. The reckless men froze to death during their expedition to the Antarctic.",
"476. The tragedy must be remembered so as not to be repeated.",
"477. The exhibition offers profound insights into ancient civilization.",
"478. Giotto is credited with sowing the seeds of the Italian Renaissance.",
"479. Bob mounted the portrait in a fancy frame, but it was upside down.",
"480. This magnificent cathedral dates back to the Middle Ages.",
"481. Asian religions inspired him to create splendid sculptures.",
"482. They explored the desert in search of buried treasure.",
"483. The millionaire insisted on acquiring the masterpiece no matter how much it cost.",
"484. Myths and legends should be handed down from generation to generation.",
"485. The linguist is fluent in several Chinese dialects.",
"486. The tribe worships its ancestors and speaks its own language, which is not familiar to us.",
"487. The anthropologist says old customs still prevail in the province.",
"488. The wicked witch cast an evil spell on the man and turned him into a bug.",
"489. They proceeded along the steep path, which was the sole access to the border.",
"490. When a big ape emerged from the cave, they got frightened and ran away.",
"491. 'Believe it or not, I saw an alien and then it vanished!' 'Give me a break!'",
"492. Quite a few people have been invited to celebrate the couple's anniversary.",
"493. It won't be long before everything is ready. In the meantime, help yourself to some snacks.",
"494. Dressed in a loud and peculiar outfit, she stood out in the crowd.",
"495. All the guests were touched by her hospitality.",
"496. Her shabby clothes were not suitable for the occasion.",
"497. That topic is too intimate to share with casual acquaintances.",
"498. When Tom gets drunk, he gets crude and offensive. Stay away from him.",
"499. He could hardly comprehend what she was implying.",
"500. Bob felt embarrassed when he was teased in front of some girls.",
"501. His ambiguous reply made her all the more irritated.",
"502. Bob is very timid and blushes when chatting with girls.",
"503. Nick looks down on anyone who comes from a rural area.",
"504. 'What's the matter, Bob? You look so miserable.' 'Leave me alone. It's none of your business.'",
"505. Although Bob was in disguise, I recognized him at a glance.",
"506. 'What are you chuckling about?' 'Bob, you have your sweatshirt on backwards!' 'Oops!'",
"507. He is not good at making friends and always keeps to himself.",
"508. Having found no place he felt he belonged, he was extremely uneasy and lonely.",
"509. I found it pretty hard to adjust to my new surroundings.",
"510. I felt utterly out of place among those sophisticated people.",
"511. To tell the truth, I don't like classical music. On the other hand, Molly is really into it.",
"512. Bob derives pleasure from observing insects.",
"513. 'How about playing cards or something for a change?' 'Sorry, I'm not up for it.'",
"514. 'After you.' 'No, please, you go ahead.' 'Thanks.' 'You're welcome.'",
"515. His niece is sociable and mature for her age. She could pass for twenty-something.",
"516. 'Take care of yourself and say hi to your family for me.' 'I will. See you later.'",
"517. I'm looking forward to hearing from you. Sincerely,",
"518. Can you spare a minute? I'd like to discuss something of importance to both of us.",
"519. It may seem trivial to you but for me it's worth paying attention to.",
"520. As far as Bob is concerned, anything goes. By contrast, Jane is very cautious.",
"521. After an awkward pause, Bill took her by the hand and dragged her upstairs.",
"522. Bill just wanted to comfort Monica, but she interpreted it as romantic interest.",
"523. After making sure she was sound asleep, he crept out of the room and set off.",
"524. Between you and me, Lisa, I came across Nick passionately embracing a woman.",
"525. Such a remark is open to misunderstanding.",
"526. 'I can't stand it anymore!' 'Calm down. I'll come over as soon as possible.'",
"527. Don't take it literally. He is inclined to exaggerate.",
"528. 'You should apologize to Lisa for making fun of her. You went too far this time.' 'Yeah... I will, sometime when she's in a better mood.'",
"529. 'Lisa, are you getting along with Nick?' 'Once in a while, I think of divorcing him.' 'You must be kidding!'",
"530. In tears, she tore up his letter and threw it away.",
"531. 'Jennifer deceived me!' 'You should have known better than to trust her.'",
"532. Tom regretted having wasted a great deal of his life.",
"533. I cannot look back on my adolescence without feeling depressed.",
"534. 'Jennifer left me for another guy.' 'Oh, you must be upset.' 'Not really. I'm used to it.'",
"535. 'No wonder she didn't show up to see him off.' 'How come?' 'They broke up.' 'Oh, what a pity!'",
"536. 'Living here all by myself is torture!' he sobbed.",
"537. 'To be honest, I'm crazy about Ken because he's brave, self-confident, and never afraid of taking risks.' 'If I were you, I'd ask him out!'",
"538. 'I've been going with Jennifer on and off for ages.' 'You're as indecisive as ever. Isn't it about time you settle down?'",
"539. 'It dawned on me that I had been taken in by Jennifer all along.' 'How naive! Didn't you see through her?'",
"540. Even though she is seeing someone else, I won't give her up.",
"541. 'Hi, Jane. What's up?' 'Not much. How about you?' 'I got married to Jennifer.' 'Wow! Congratulations!'",
"542. Whenever you're in trouble or feeling down, I'll be there for you.",
"543. 'Delight' is the opposite of 'sorrow'.",
"544. 'Jennifer went so far as to call me an idiot and she wouldn't take it back.' 'Serves you right! You provoked her, didn't you?'",
"545. 'Why do you put up with her arrogance? She's just taking advantage of you.' 'Shut up!'",
"546. Take your time. I know you need a couple of days to reflect on it.",
"547. Bob has to get through this ordeal on his own.",
"548. Flies and mosquitoes interfered with his meditation.",
"549. The sacred ritual took place after being postponed twice.",
"550. All at once, the Buddhist priest burst into laughter, spoiling the solemn atmosphere.",
"551. Cover your mouth when you cough, sneeze, or yawn.",
"552. 'One of her relatives passed away three days ago.' 'Oh, that's too bad. I'm so sorry.'",
"553. Besides attending the funeral, she needs to make all the arrangements.",
"554. 'I feel for you, Jane. Grief doesn't fade away quickly.' 'I'm OK. I'll get over it.'",
"555. She cherishes the precious memories of her childhood.",
"556. 'Speaking of Jennifer, she got engaged to a businessman.' 'I'm at a loss for words! I hope she won't break it off.'",
"557. These days, the motives for marriage are not necessarily pure. Take Jennifer for example.",
"558. Go easy on Bob. You know, he's been going through a rough period recently.",
"559. 'By the way, do you have the time?' 'Let's see ... it's a quarter to eight.'",
"560. 'Let's call it a day, Bob. I'm starved.' 'Yep. I'll buy you dinner.'",
);

$duoKorean = array(
"1. 우리는 개인의 의지를 존중해야 한다.",
"2. 마음을 편히 가져. 다 잘 될 거라고 나는 확신해.",
"3. 비관적인 인생관을 버리고, 항상 긍정적인 태도를 유지하라.",
"4. 당신은 태어난 나라나 성별, 또는 신조에 관계없이 누구에게나 공평해야 한다.",
"5. 평등은 헌법에 의해 보장된다.",
"6. 그는 기둥에 기대어 자유의 여신상을 물끄러미 바라보았다.",
"7. 한 여인이 희미한 향수 냄새를 풍기면서 내 옆을 지나갔다. 그것은 내게 옛 여자 친구를 생각나게 했다.",
"8. '낫토'는 냄새는 심하지만 맛은 아주 좋다.",
"9. '땀으로 흠뻑 젖었어.' '저리가! 냄새나. 샤워해.'",
"10. Bob은 몹시 흥분해서 현실과 허구를 거의 구별할 수 없었다.",
"11. 곧 출판될 그의 소설은 산문과 그의 시적 재능을 결합시킨 것이다.",
"12. 다음 달에 그 백과 사전의 최신판이 나올 것이다.",
"13. Yamada 씨가 흥미로운 옛날 이야기를 쉬운 일본어로 번역했다.",
"14. 다음 단락은 유명한 우화로부터 인용한 것이다.",
"15. '현대 문학을 잘 아십니까?' '그것에 대해서는 거의 모릅니다.'",
"16. 때때로 나는 'curve'와 'carve'를 혼동한다.",
"17. 부끄러워하지 말아요. 당신의 발음은 거의 정확해요.",
"18. 이 기사에는 어휘력을 향상시키고자 하는 사람들을 위한 비법이 들어 있습니다.",
"19. 그의 가장 최근의 작품이 시청에 전시되어 있다. 그것들은 말로 표현할 수 없을 정도로 멋지다.",
"20. '좀 좁혀 앉아주시겠어요?' '아, 미안합니다. 제가 이렇게 자리를 많이 차지하고 있는 줄 몰랐습니다.'",
"21. '이 추한 물체는 뭐야?' '이건 추상 예술 작품이야.'",
"22. 나는 Richie에게 100달러를 빌려달라고 부탁했지만, 그는 '나도 돈이 없어.'라고 말하며 거절했다.",
"23. '저는 물건이 싸게 판매되면, 충동 구매를 하는 경향이 있어요.' '저도 그래요.'",
"24. 실제로 보통 사람들에게는 그런 사치품을 구입할 여유가 없다.",
"25. 우리가 예측했던 대로 실업률은 3/4분기에 계속 상승했다.",
"26. 나는 지출을 줄여야 하므로, 이제부터는 하루 단위로 지출을 기록하려고 한다.",
"27. 어쨌든 조합측은 어느 정도 타협을 해야 한다.",
"28. 유능한 정비사는 인기가 있으므로 상당한 임금을 받을 수 있다.",
"29. 대통령은 복지 개혁을 실행하기 위한 구체적인 계획을 공표했다.",
"30. 그의 정책은 틀림없이 형편없는 결과를 초래할 것이다. 철저한 재검토가 필요하다.",
"31. 사회의 고령화가 불가피하다는 것은 말할 것도 없다.",
"32. 이 표를 봐 주십시오. 청소년 비행이 심각한 비율로 증가하고 있다는 것을 나타내고 있습니다.",
"33. 많은 상업 지구에는 수 년간 매물로 나와 있는 공터가 많이 있다.",
"34. 대도시의 인구 밀도가 서서히 낮아지고 있다.",
"35. 거의 틀림없이, 앞으로 몇 년간 출생률은 꾸준히 감소할 것이다.",
"36. 그 발전소는 멀리 떨어진 마을에 전기를 공급하고 있다.",
"37. 허가없이는 이 장치를 조작할 수 없습니다.",
"38. 사실, 주민들은 방사능에 노출되어 있다.",
"39. 핵 에너지의 잠재적인 위험성은 아무리 강조해도 지나치지 않는다.",
"40. 몇 년 동안 언론은 그 문제를 간과했다. 그러나 지금은 오히려 그것을 지나치게 중시하고 있다.",
"41. 그 농부는 곡물을 재배할 뿐만 아니라 식료품 가게도 운영하고 있다.",
"42. 그 연구소는 1960년대 후반에 설립되었다.",
"43. Starr 씨에게 직접 상담하는 것이 어떻겠습니까? 그는 이 주변에서 단연코 가장 유명한 변호사거든요.",
"44. 만약을 위해 메모해 두겠습니다. 제가 기억력이 나쁘거든요.",
"45. 변호사는 의뢰인에게 보험 회사를 상대로 법적 조치를 취할 것을 권했다.",
"46. 그들은 그의 부상에 대해 보상받을 권리가 있다.",
"47. 독감의 유행으로 현재까지 200명이나 되는 사람들이 죽었다.",
"48. 그 알약들의 효과는 강력하지만 지속성이 없다.",
"49. 그는 손톱을 물어뜯는 버릇이 있다. 그것은 정말 소름끼친다.",
"50. 할머니께서는 나의 아들을 안으시려고 몸을 굽히시다가 무리하셔서 허리를 다치셨다.",
"51. 어깨가 결린다면 약초 치료를 시도해 보아라.",
"52. 의학의 비약적 발전은 인류 전체에게 엄청난 혜택을 초래했다.",
"53. 클론 기술은 인간에게는 물론 소에게도 응용해서는 안 된다. 그것은 금지되어 있다.",
"54. 고래는 포유 동물로 분류된다.",
"55. 진화론은 나의상상력의 범위를 넘어선다.",
"56. 그 생물학자는 자신의 역사적 발견에 자긍심을 가지고 있으며, 그것에 대해 자랑스럽게 말하는 것을 꺼리지 않는다.",
"57. 윤리적인 이유에서 그들은 이른바 유전자 치료에 반대하고 있다.",
"58. 그 병의 초기 증상은 고열이 나고 목이 아픈 것입니다.",
"59. 뇌의 구조는 복잡하다.",
"60. 질병 때문에 몇몇 대표자들은 연례 회의에 결석했다.",
"61. 나의 사위는 서서히 위암을 극복해 가고 있고, 지금 그의 기분은 좋은 상태이다.",
"62. '이거 가짜지, 그렇지?' '이봐, 진짜 골동품이라구.' '설마!'",
"63. '그 밖에 더 필요하신 것은 없나요?' '그게 전부입니다.' '여기서 드시겠습니까, 가지고 가시겠습니까?' '가지고 갈 겁니다.'",
"64. '이 깔개는 얼마에요?' '세금을 포함해서 100달러입니다.' '그럼 이것으로 하겠습니다.'",
"65. 이 바지는 당신에게 어울리지 않는 것 같네요. 이것을 입어 보세요. 지금 대단히 유행하고 있거든요.",
"66. 그는 '거스름돈은 됐습니다.'라고 말하고는 급히 택시에서 내렸다.",
"67. 저희 고객들은 약간의 추가 요금으로 배달 서비스를 이용하실 수 있습니다.",
"68. '이건 내가 낼게.' '안돼. 우리가 외식할 때마다 항상 네가 내잖아.' '그래, 알았어. 그럼 각자 내자.'",
"69. 나는 쇼핑 센터를 돌아다니다가 우연히 Ken을 만났다.",
"70. 나는 현금이 부족해서, 지난 주에 은행 구좌에 넣어 두었던 100달러를 인출했다.",
"71. 그녀는 집에 오는 도중에 핸드백을 강탈당했다.",
"72. '그것 참 이상하군! 어떻게 그런 일이 생겼는지 말해 줘.' '나중에 설명할게.'",
"73. 내가 약속을 어긴 벌로서 부모님은 6시로 귀가 시간을 정했다.",
"74. 속담에도 있듯이, '목적이 수단을 정당화한다.' (거짓말도 방편이다.)",
"75. 이제 아무도 의지할 수 있는 사람이 없다는 것을 알았기 때문에, 나는 자립해야 할 것이다.",
"76. 의장은 내 말을 가로막으며  '논의는 끝내고, 가부를 결정합시다.'라고 말했다.",
"77. 우리는 회의에서 솔직한 의견을 교환했지만 아직까지 이 문제에 대한 전체의 의견이 일치하지 않는다.",
"78. '당신은 그와 의견이 일치하나요, 아니면 다른가요?' '저는 그와 같은 생각입니다.'",
"79. 엄밀히 말하면, 그의 견해는 나의 견해와는 약간 다르다.",
"80. 다시 한 번 설명해 주시겠습니까? 당신이 말하려고 하는 것을 이해하지 못했거든요.",
"81. 처음에는 아무도 나를 지지하지 않았지만, 결국 나는 모두가 내 계획에 찬성하도록 설득했다.",
"82. '너의 불굴의 노력, 용기, 그리고 지혜에 감탄했어.' '빈말이라도 기쁘군!'",
"83. 나는 결정을 내릴 때 논리가 아니라 본능에 따른다.",
"84. 그는 독창적이고 현명한 해결책을 생각해 내고는 즉시 실행에 옮겼다.",
"85. 객관적인 관점에서 보면, 전자가 후자보다 못하다.",
"86. 당신의 생각은 이론상으로는 훌륭하지만, 실제로는 가능하지않을 것이라고 생각합니다.",
"87. 우리는 그가 상대에게 이길 것을 기대했지만, 그는 우리의 기대에 부응하지 못했다.",
"88. 뜻밖에도, 그들이 최선을 다해 노력했음에도 불구하고 그들의 임무는 완전히 실패로 끝났다.",
"89. 그녀의 천부적인 재능은 직접적인 경험 부족을 보충해 준다.",
"90. 그녀는 어떤 장애도 극복할 수 있는 뛰어난 능력을 가지고 있다.",
"91. 당신의 확실한 지원이 없었다면 그 거래는 성립되지 않았을 것입니다. 감사하게 생각하고 있습니다.",
"92. 기내에 가연성 물질을 가지고 들어가는 것은 금지되어 있습니다.",
"93. 사소한 사고 때문에 우리가 비엔나로 갈 비행기 편이 지연되었다.",
"94. 비행기가 폭발하면서 바다에 추락하여, 비행기에 타고 있던 모든 사람들이 사망했다.",
"95. 그들은 밤낮으로 쉬지 않고 그 추락 사고의 원인을 조사하고 있다.",
"96. 불행하게도 그 대참사에서 살아남은 승객은 거의 없었다.",
"97. 항공 전문가는 통계를 세밀하게 분석했다.",
"98. 전 직원을 대표해서 희생자 분들에 대해 유감의 뜻을 말씀드리고자 합니다.",
"99. 어떤 의미에서 그는 그 참사에 책임이 있다.",
"100. 차량에 결함이 없는지 3개월에 한 번씩 검사받는다.",
"101. 나는 우리집 전기 요금이 그렇게 많이 나왔다는 것을 알고 몹시 놀랐다.",
"102. '수도꼭지 좀 잠궈!'하고 엄마는 몹시 화를 내며 소리치셨다.",
"103. 음식이 상하지 않도록 뚜껑을 꽉 닫으세요.",
"104. '가위 좀 빌릴 수 있을까요?' '물론이에요, 여기 있어요.'",
"105. 바늘과 실 대신에 투명한 접착제를 사용해도 괜찮습니다.",
"106. 내가 이 천을 염색했더니 줄어버렸다.",
"107. 이 가죽 재킷을 버려야겠어. 팔꿈치가 닳아서 해졌어.",
"108. 그 혼합물에 밀가루를 더 넣고 걸쭉해질 때까지 섞으세요.",
"109. '남은 음식을 어떻게 하지?'  '당분간 냉장고에 넣어 둬. 나중에 전자렌지로 다시 데울게.'",
"110. 새로운 컴퓨터에 모든 돈을 쓸 수도 있었지만, 다시 생각해 보고 만약의 경우를 위해 일부는 남겨두기로 했다.",
"111. 휴대 전화는 약간 필수품이 되었다. 그래서 난 휴대 전화 없이는 살 수 없다.",
"112. 의자에 느긋하게 앉아 쉬려고 하자마자 아내는 내게 집안일을 할 것을 요구했다.",
"113. 그녀는 아기를 눕히고 자신도 아기 옆에 누웠다.",
"114. 이 물건 좀 치워 줘. 방해가 돼.",
"115. 아이들은 공룡 흉내를 내며 놀다가 어머니에게 야단맞았다.",
"116. 그가 선반에 부딪쳤을 때 고가의 도자기가 떨어져 산산조각이 났다.",
"117. '잠시만 우리 아이들을 좀 봐 줄 수  있어? Ken을 데리러 가야 하거든.' '알았어.'",
"118. 우리 이웃집 사람은 그의 정원이 엉망진창이 되었다면서 우리에게 호되게 설교를 했다.",
"119. Dolly는 모든 면에서 그녀의 언니와 닮았어. 너는 그들 둘을 구별할 수가 없을 걸.",
"120. 일반적으로 쌍둥이들은 닮은 점이 많다.",
"121. 설거지, 세탁 등 그런 일을 하는 것에 진절머리가 났다.",
"122. 내가 가장 좋아하는 여가 선용 방법은 호숫가를 산책하는 것입니다. 그것은 즐겁습니다.",
"123. '난 지쳤어. 그늘에서 좀 쉬자.' '그러자.'",
"124. 'Bob, 이 자동 판매기는 고장났어.' '뭐야! 나 목이 말라 죽을 것 같다구!'",
"125. 그는 배고픔과 피로로 정신을 잃었지만 얼마 후 의식을 되찾았다.",
"126. 단 한 점의 가구를 제외하고는 강당은 텅 비어 있었다.",
"127. 집세만 싸면 어떤 맨션이든 상관없습니다. 저는 집에 대해 까다롭지는 않습니다.",
"128. 60세인 그의 사촌이 호수 옆 부동산을 상속했다.",
"129. 잡담은 이쯤 해 두고, 본론으로 들어갑시다.",
"130. Lucy는 그녀에게 억지로 계약서에 서명하도록 밀어붙이는 판매원에게 화를 냈다.",
"131. 우리에게 주식 투자할 마음이 나지 않게 할 만한 요인들이 상당히 많이 있다.",
"132. 일본은 여러 가지 원료를 수입하고 공업 제품을 수출한다.",
"133. 일본은 경제 발전의 과정에서 전통적 가치관을 버렸다.",
"134. 세계는 전에 없던 위기에 직면해 있다.",
"135. 요컨대, 그 규제의 목적은 국내 산업을 보호하는 것이다.",
"136. 일본은 세계적인 경쟁력을 유지하기 위해서 대폭적인 규제 완화에 진지하게 착수해야 한다.",
"137. 우리는 위험에 처해서도 필사적인 사람들을 모른척 할 수 없다.",
"138. 의회는 개발도상국들에게 재정 원조를 하기로 결의했다.",
"139. 영국의 군주제는 폐지되어야 한다고 말하는 사람도 있습니다. 당신은 어떻게 생각하십니까?",
"140. 그들은 공격을 피할 안전한 장소를 찾았지만 숨을 만한 곳이 없었다.",
"141. 군비 축소에 있어서 양국이 큰 진전을 이루리라는 전망은 거의 없다.",
"142. 교섭이 진행 중이다. 곧 그들은 중요한 국면을 맞게 될 것이다.",
"143. 노예들은 자신들의 운명을 바꾸기를 갈망했다.",
"144. 귀족들은 마음껏 특권을 남용했다.",
"145. 결국, 혁명 그 자체는 아무런 성과도 가져오지 못했다.",
"146. Bob이 '나는 반대야!'라고 하며 우리의 대화에 끼어들었다. 그러나 모두들 그를 무시했다.",
"147. 일부러 우리들은 그의 순서를 건너뛰었다.",
"148. 그는 누군가가 괴롭힘을 당하는 것을 봤지만, 못 본 척했다.",
"149. Nick과 내가 시험에서 부정 행위를 했을 때, 나는 정학 처분을 받았다. Nick은 처벌을 교묘히 피했다.",
"150. 그들은 Richard의 부와 지위에 대한 질투로 그에게 적의를 품고 있다.",
"151. 그 사람 너무 싫어 ! 마치 자기가 대단한 사람인 것처럼 행동하잖아.",
"152. 우리의 칭찬에도 불구하고 그는 얼굴을 찌푸리며 고개를 돌려버렸다. 그는 몹시 무례했다.",
"153. 그 막대한 재산은 자기가 자유롭게 쓸 수 있는 것이라고 그는 주장했다.",
"154. 네가 고집을 부리면 부릴수록 더욱 더 고립된다.",
"155. '빙빙 돌려서 말하지 마 ! 나보고 어떻게 하라는 말이야?' '서두르지 말고 기다려 봐. 시간이 지나면 알게 될 거야.'",
"156. 과제는 전자 메일로 6월 10일 오후 5시까지 제출해 주십시오.",
"157. Joe는 결코 근면하지 않다. 그런 까닭에 그는 수학에서 또 낙제했다.",
"158. 그의 논문은 이해할 수가 없다. 우선 주제가 애매하다.",
"159. 그의 소논문은 간결하고 요령있는 것이다.",
"160. '이 복잡한 문제를 어떻게 처리할 작정이야?' ' 내게 맡겨. 식은 죽 먹기야.'",
"161. 'Nick, 이것을 제출하기 전에 쭉 훑어봐 줬으면 해.' '미안하지만, 지금은 내가 몹시 바빠.'",
"162. '마감 시간을 맞추지 못하면 어떻게 하지?' '틀림없이 그가 화낼 거야 !'",
"163. 그의 요약은 글씨가 엉망인 것 외에는 더 이상 바랄 것이 없다. ",
"164. 그 전제가 타당한지 아닌지 잘 생각해야 한다.",
"165. 우선 과학 용어에서는 엄밀한 정의가 요구된다.",
"166. 무엇보다도 먼저, 공식을 암기하세요.",
"167. 체적을 계산할 경우, 세로와 가로와 깊이를 곱합니다.",
"168. 통 밑바닥에 아주 작은 금이 가 있는 것을 발견했다.",
"169. 이 장에서는 기하학의 개념에 초점을 맞추겠습니다.",
"170. Phil은 실용적인 기술보다는 학문적인 주제에 훨씬 더 흥미를 가지고 있다.",
"171. '이 현미경에 뭔가 문제가 있어. 수리받아야겠어.' '좀 보여줘. 내가 고칠 수 있을지도 몰라.'",
"172. 'instrument가 무엇입니까?' '예를 들면 온도계나 기압계와 같은 그런 기기입니다.'",
"173. 그 미립자는 육안으로 간신히 보인다.",
"174. 근육 조직은 엄청난 수의 세포로 이루어져 있다.",
"175. 이 물질은 대부분 수소와 산소로 구성되어 있다.",
"176. 정확한 기온은 섭씨 22.68도입니다.",
"177. 'Naomi는 자신의 완벽한 몸매를 과시하고 싶어해. 나도 그녀처럼 날씬하면 좋겠어. 그녀가 부러워.' '다이어트를 시작하면 되잖아.'",
"178. 난 Naomi에게 첫눈에 반했어. 3개월 후, 과감히 그녀에게 프로포즈를 했지만 거절당했지.",
"179. 나는 우연히 그 사람을 만났어. 그는 상냥하고 똑똑해. 게다가 독신이야 !",
"180. 그의 조카는 겸허하고 인정 많은 사람이 되도록 교육받았다.",
"181. 부모님께 Bob을 소개해 드리자 두 분은 곧 그를 좋아하시게 되었다.",
"182. 사람은 겉모습이 아니라 내실로 판단되어야 한다.",
"183. '중요한 것은 너의 직함이 아니야. 확실히 그래 !'라고 Bob은 강한 어조로 말했다.",
"184. 자수성가한 사람이 말했듯이, '선견지명이 있는 사람은 결국 성공하게 된다.'",
"185. 젊음은 영원한 것이 아니라는 것을 기억해 둬라.",
"186. 나는 도대체 모두들 왜 그렇게 Bob을 경멸하는지 이해할 수가 없다.",
"187. 그는 계속해서 바보같은 실수를 하기 때문에 비웃지 않을 수 없다. 그는 자신의 잘못을 깨닫지 못할 것이다.",
"188. 설상가상으로 그는 자신이 우리를 화나게 하고 있다는 것조차 모르고 있다.",
"189. 서두르다가 실수로 장갑을 안팎을 뒤집어서 꼈다.",
"190. Dave는 뚱뚱하고 바보스럽다. 얕은 개울을 뛰어넘다가 비틀거려 발목을 삐었다.",
"191. '난 고소 공포증이 있어.' '너 겁쟁이구나 !'",
"192. 소극적인 사람은 다른 사람 앞에서 자신을 표현하는 일이 거의 없다.",
"193. Nick은 나에게 미신은 근거가 없다는 것을 납득시켰다.",
"194. 주사를 생각하면 무서워서 몸이 떨린다.",
"195. Bob은 천성이 게을러서 종종 주어진 일을 소홀히 한다.",
"196. Bob이 일하고 있는 동안  Jennifer는 집에서 시시한 멜로 드라마에 빠져 있었다.",
"197. Bob은 만화를 좋아하지만, 나는 그것들을 높이 평가하지 않는다. 사실 그것들은 사람들을 지루하게 한다.",
"198. 그가 내 눈을 똑바로 보지 못하는 것으로 보아, 나에게 뭔가 숨기고 있다고 생각했다.",
"199. 그녀는 참을 수가 없어 그의 멱살을 잡고 욕을 했다.",
"200. 우리가 때때로 말다툼을 한다는 것은 인정하지만, 보통은 서로 사이좋게 지낸다.",
"201. '너의 집에 들러도 괜찮겠니?' '물론이지. 사양하지 말아줘 ! '",
"202. 좀 기다려. 금방 돌아올게. 끊지마! (전화에서)",
"203. 너를 우리집에 머물게 할 수 없어. 그 이유 중 하나는 때때로 우리 아버지가 잠시 들르시거든.",
"204. Jennifer가 물끄러미 서 있는 동안 Bob은 보도를 따라 왔다갔다 하고 있었다.",
"205. '화해하자, Lisa.' '내가 있는 걸 당연하게 생각하지 마. 우리 이번엔 영원히 끝이야. 진심이야!'",
"206. 이봐! Lisa, 그렇게 감정적으로 하지 마. 너에게 상처 주려던 것은 아니었어. 얘기를 해 보자.",
"207. '당신은 나를 배신했어!' '용서해줘. 내가 어떻게 보상해 줄 수 있을까?'  '되갚아 줄 거야!'",
"208. 자신의 죄를 감추기보다는 고백해야 한다.",
"209. 약속을 지키세요. 그렇지 않으면 평판이 떨어질 것입니다. ",
"210. Bob은 자신의 도덕적 신조를 지키며, 성실한 것이 결국에는 보상을 받으리라고 믿고 있다.",
"211. '기운 내! 어쩔 수 없었잖아.' '난 최선을 다 했어.' '알아. 지난 일에 연연하지 마. 처음부터 다시 하는 거야!'",
"212. 'Jane, 부탁이 있는데, Times 광장까지 좀 태워 줘.' '그러고 싶지만, 지금은 시간이 없어.'",
"213. 언제나처럼 Mike는 정각에 나타났다. 그는 정말 시간에 정확하다.",
"214. 얼마 전 혼잡한 간선 도로 한가운데에서 가솔린이 떨어져 버렸다.",
"215. 내 앞을 달리던 트럭이 미끄러지면서 전복되어 운반되던 짐이 도로에 사방으로 흩어졌다.",
"216. 그는 전적으로 운이 좋아 충돌을 피할 수 있었던 것이라고 회상했다.",
"217. 긴급할 때에는 곧바로 나의 대리인과 연락을 해 주십시오.",
"218. 'Jane, 우리 어디로 가고 있는 거야?' '길을 잃은 것 같아. 다른 방향으로 와 버렸어.' '뭐야! 길 한쪽에 차를 세워 봐!'",
"219. 나의 녹슨 Ford가 고장이 나서 교차로를 막아버렸다.",
"220. 그것은 표면에 미세한 상처나 홈이 많아서 닦아도 소용이 없다.",
"221. '이봐, 교통 체증에 걸려버렸잖아!' '흥분하지 마, Joe. 지름길로 가자. 제시간에 도착할거야.'",
"222. '타이어가 펑크나 버렸어. 좀 도와 줄 수 있니?' '기꺼이 도와 줄게.'",
"223. 제동이 걸리지 않는 구급차가 하마터면 보행차를 칠 뻔했다.",
"224. 그는 화성에 원시적인 생물이 한때 살았다고 주장한다.",
"225. 승무원들은 우주 비행을 준비하느라고 바쁘다.",
"226. 그들은 무중력 상태에서 일련의 실험을 했다.",
"227. 많은 천문학자들은 우주가 무한히 팽창할 것이라고 생각한다.",
"228. 우주 비행사들은 뜻밖에 터져나오는 박수 갈채로 환영받았다.",
"229. 위기에 직면한 지구를 지키려고 기금이 마련되었다.",
"230. 대홍수로 현지의 교통망이 마비되었다.",
"231. 적도는 지구를 두 개의 반구로 나눈다.",
"232. 나는 모피 코트를 입기 위해 동물을 올가미로 포획하는 것은 잔혹한 짓이라고 생각한다.",
"233. 그 단체는 야생 동물의 보호에 있어서 가장 중요한 역할을 담당하고 있다.",
"234. 많은 약한 생물종이 멸종의 위기에 처해 있다.",
"235. 오래 지속되는 가뭄이 수확에 심각한 피해를 초래했다.",
"236. 열대우림이 광범위하게 급속히 소멸되고 있습니다. 어느 정도는 산성비 때문입니다.",
"237. 지구 온난화는 이산화탄소의 배출과 직접적인 관계가 있다고 일컬어진다.",
"238. 오존층의 파괴는 환경에 영향을 미친다.",
"239. 위원회는 대기 오염을 억제하기 위해 서로 협력하도록 각국에 요청했다.",
"240. 계속 녹고 있는 빙하를 관찰하기 위해 인공위성이 궤도에 올랐다.",
"241. 석유는 하늘의 축볼일 뿐만 아니라 재앙의 근원이라고 그 생태학자는 우리에게 거듭해서 경고해 왔다.",
"242. 그 대륙은 화석 연료가 풍부하다.",
"243. 그 지역은 광물 자원이 비교적 풍부하다.",
"244. 밀은 그 지역의 농업 생산량의 대략 3분의 2를 차지하고 있다.",
"245. 수확량을 높이기 위해서는 비옥한 토양이 불가결하다.",
"246. 습기가 많은 기후는 그 반도의 특색이다.",
"247. 그 활화산은 주기적으로 분화한다.",
"248. 파나마 운하는 대서양과 태평양을 연결하고 있다.",
"249. 이 곳의 지리적 특징은 우리 현과 비슷하다.",
"250. 대개 기근이 되면 역병도 발생한다.",
"251. 괴멸적인 규모의 지진이 주의 수도를 엄습하여 수만 명의 주민이 집을 잃었다.",
"252. '조심해! 천정이 무너지고 있어!'",
"253. 태풍은 속도를 높여서 해안에 근접할 것 같다고 일기 예보에서는 말하고 있다.",
"254. '경기가 중단될지 아닐지 아직 결정되지 않았어.' ' 그게 어떻다는 거야? 나한테는 아무래도 상관없는 일이야.'",
"255. '안개가 짙은 걸.'   '정말 그렇구나. 하지만 아마 잠시 후에는 맑아질 거야.'",
"256. 대개 근대화를 서구화와 동일한 것으로 생각한다.",
"257. 많은 사람들, 특히 젊은이들에게는 도시의 문화가 매력적으로 비친다.",
"258. 'AI'는 인공지능의 약어입니다.",
"259. 가정용 전자 제품은 날마다 점점 더 편리해지고 있다.",
"260. 내 수입은 4인 가족을 부양하기에는 충분하지 않지만, 그것으로 어떻게든 해 나가는 수밖에 없다.",
"261. 홈페이지의 인기는 내용에 달려 있다.",
"262. 뒤처지지 말고 따라가야 한다. 일단 뒤처지면 따라잡기가 힘들다.",
"263. 기술이 급속히 진보하고 있기 때문에 뒤처지지 않고 따라가기가 힘들다.",
"264. 점점 많은 사람들이 그 매체의 상호 의사 전달이 가능한 특성을 이용하려고 서두르고 있다.",
"265. 혁신은 특이한 현상을 간과하지 않는 능력과 관계가 있다.",
"266. 다른 많은 회사들이 우리의 뛰어난 방법을 모방하고 있다.",
"267. 한때 황량했던 분지가 번창하는 하이테크 사업의 중심지로 변모했다.",
"268. 아직 개선의 여지는 많지만, 그의 발명품은 모든 점에서 종래의 기기보다 뛰어나다.",
"269. 그 회사의 강점은 타사에 없는 미래지향적인 전략에 있다고 여겨진다.",
"270. SONY는 이 대단한 기기에 다양한 기능을 통합시켰다. 그것은 미국 전체에서 인기를 얻고 있다.",
"271. 이 도구는 쓸모가 있기 때문에 나는 항상 그것을 가까이 둔다.",
"272. '대개 소비자는 질보다는 양을 선호합니다.' '요즘은 정반대입니다.'",
"273. 명백히 그 광고는 10대의 젊은 층을 목표로 하고 있다.",
"274. 현재 건설 중인 그 공장은 하루에 1,000대의 비디오를 조립하게 된다.",
"275. 효율적인 기계가 육체 노동을 대신한다.",
"276. 당시 그 거대한 기업이 국내의 상업을 사실상 독점하고 있었다.",
"277. 제한이 해제되면서 수 천 개의 새로운 기업이 탄생했다.",
"278. 어리석은 새 사업의 결과, 그는 파산의 위기에 처해 있다.",
"279. 작년과 비교해 볼 때, 판매의 관점에서 보면 사업은 좋아지고 있다. 하지만 아직 이익을 전혀 내지 못하고 있다.",
"280. '해외 지점으로 전근하게 됐어.' '어머, 적적해지겠구나. 편지라도 보내.'",
"281. 그가 출장 중인 동안 그의 부인이 사내 아이를 출산했다.",
"282. 겉으로 보기에는 그 일이 Nick의 부담을 가중시킬 수도 있기 때문에 Nick은 그것을 받아들이고 싶어하지 않는 것 같다.",
"283. Bob은 오늘밤 그녀와 데이트를 하려고 했으나 야근을 해야 했다.",
"284. '늦어도 금요일까지는 손실의 견적을 내 주십시오.' '어떻게든 해 보겠습니다.'",
"285. '너만 믿을게, Nick.' '좋아. 그건 내가 맡아 처리할게.' '고마워, 정말 고맙게 생각하고 있어.' '천만에.'",
"286. 그는 상사가 옆에 있을 때는 열심히 하는 체한다.",
"287. 그는 동료들을 희생시켜 승진했다. 그런 자신을 부끄럽게 생각해야 할 것이다.",
"288. 경기 후퇴가 시작되자, 임시직 사원들은 잇따라 일시 해고를 당했다.",
"289. 최근에는 많은 사람들이 본의 아니게 취직을 못 하고 있다. 그것은 누구의 책임일까?",
"290. 내가 비관적이 되어서, 예전에는 전혀 신경쓰지 않았던 것들에 대해 걱정하고 있다.",
"291. 오늘날에는 샐러리맨들조차 대단한 곤란에 직면하고 있다.",
"292. 당국은 통화를 안정시키기 위해 필사적으로 노력하였으나 헛일이었다.",
"293. 우리는 일본의 막대한 적자를 줄이는 것이 무엇보다도 긴급한 일이라는 결론에 도달했다.",
"294. 앙케이트 용지가 무작위로 배포되었다.",
"295. 아래의 빈 칸 부분에 기입해 주시면 됩니다.(흑색 또는 청색 잉크로 써 주십시오.)",
"296. 10%의 할인에다 무료로 선택 관광을 고르실 수 있습니다.",
"297. 각 목적지까지의 왕복 요금은 아래와 같습니다.",
"298. '사전에 예약 확인하는 것을잊지 말아라.' '그럴게요.'",
"299. 늦어도 출발 시각 45분 전에는 탑승 수속을 반드시 완료시켜 주십시오.",
"300. 내 짐에 이름표를 붙였는데, 금방 떨어져 버렸다.",
"301. 이 소포들은 평균 2파운드의 무게가 나간다.",
"302. 비닐로 만들어진 이 쓰레기 봉투에는 유해한 화학 물질이 들어 있지 않다.",
"303. 이 회중 전등은 밝기가 어두워지고 있다. 새 건전지로 갈아 끼워야 겠다.",
"304. 죄송하지만, 뉴욕 시내로 가는 셔틀 버스는 얼마나 자주 다닙니까?",
"305. 그 모텔은 400명이나 되는 많은 숙박객들을 투숙시킬 수 있다.",
"306. 이 스위트 룸은 우리가 가지고 있는 맨션보다 3배가 넓다.",
"307. 이 시설 내에서 쓰레기를 버리면 최고 500달러의 벌금에 처해지게 된다.",
"308. 저 레스토랑은 항상 붐비기 때문에 미리 예약을 하는 것이 좋다.",
"309. '식사를 방해해서 미안하지만, 은밀하게 상담하고 싶은 것이 있어.' '나중에 만나러 갈까?'",
"310. 요리사는 그의 엄청난 식욕에 매우 놀랐다.",
"311. '저 아래에서 무슨 일이 일어나고 있니? 궁금한데.' '글쎄, 잘 모르겠어.'",
"312. 흥분한 팬들은 Michael을 한 번 흘끗 보기라도 바라며 뒷문에 몰려 있었다.",
"313. 유명인과 마주치자마자 그들은 사인을 해 달라고 부탁했다.",
"314. 나는 해외에 갈 때마다 시차병과 설사로 고생한다.",
"315. '현기증이 느껴지면서 구역질이 나려고 해.' '얼굴이 창백해 보여.'",
"316. 진통제를 드세요. 곧 두통이 가라앉을 것입니다.",
"317. '왠지 몸이 안 좋은 것 같아.' '하루 휴가를 내도록 해.'",
"318. 이 음료에 포함되어 있는 성분 중에는 유해한 것도 있는데, 특히 임신 중인 산모에게 그렇다.",
"319. 충분한 영양 섭취는 유아의 발육에 아주 중요하다.",
"320. 적당한 운동은 혈액 순환을 활발하게 한다.",
"321. 의사는 내게 당분간은 술을 삼가라고 충고했다.",
"322. 나는 꼭 몸을 건강하게 하고 체중 감량도 하고 싶어서 매일 아침 수영하러 간다.",
"323. 그는 어제 늦게까지 안자더니 심한 감기에 걸렸다.",
"324. 외과 의사는 그를 설득해서 장기 이식 수술을 하게 했다.",
"325. 아버지께서 병으로 누워 지내시기 때문에 우리가 교대로 돌봐 드리고 있다.",
"326. 우리의 가설은 정크 푸드의 과잉 섭취가 조기 사망의 원인이 된다는 것이다.",
"327. 정부는 감염의 확대를 방지하기 위한 적절한 조치를 취하지 않았다.",
"328. 그 대신은 내각을 사임하지 않을 수 없었다.",
"329. 많은 사람들은 현행 의무 교육 제도가 시대에 뒤떨어진 것이라고 생각하고 있다.",
"330. 많은 사람들은 내가 큰 목표를 실현시키도록 격려해 주었다.",
"331. 자신의 꿈을 실현시키기 위해 그는 학교를 중퇴하고 동경으로 향했다.",
"332. '무슨 일을 하고 계십니까?' '대학생입니다. 하버드 대학 1학년입니다.' '전공은요?' '철학입니다.'",
"333. 2001년 4월 1일부터 수업료가 약 10% 인상될 것이다.",
"334. '장학금을 신청해야 할지 말아야 할지 고민하고 있어.' '한번 해 봐!'",
"335. 그는 Keio 대학을 졸업하자마자 곧 가업을 이어받았다.",
"336. 군의 규율은 엄격하기 때문에 당신은 군대와 어울리지 않는다.",
"337. 나는 어떤 희생을 치르더라도 극작가로서 생계를 유지하기로 결심했다.",
"338. 그는 어른이 되면서, 사물을 종합적인 시야로 볼 수 있게 되었다.",
"339. 사회 통념에 따르는 것은 단일 민족으로 구성된 우리 지역 사회에서 필수 불가결한 요소이다.",
"340. 오로지 회사를 위해 일하기보다는 나의 길을 가겠다. 틀에 끼워 맞추려고 해 봤자 내겐 아무런 성과가 없다!",
"341. Tom의 성격은 그의 삼촌을 닮았다. 그러니까, 선천적으로 고집불통이다. 그는 절대로 꺾이지 않는다.",
"342. 시기가 무르익으면 대담하게 밀어붙이는 거야! 내가 네 옆에 있을게.",
"343. 나의 신념을 지킬 것이며, 어떤 위협에도 굴하지 않을 것이다.",
"344. '내 약점을 극복할 수 있다면 좋을텐데.' '그것은 너하기 나름이야.'",
"345. 자신의 재능을 증명하기 위해 좀처럼 없는 이 기회를 최대한으로 이용해야 한다.",
"346. 나를 실망시키지 마. 나는 너를 굳게 믿고 있어. 너라면 잘 할 수 있을 거야!",
"347. 관객들은 그녀의 우아한 연기에 감동받았다.",
"348. 1995년 Ando 씨는 건축에 있어서 가장 권위 있는 상을 수상했다.",
"349. 역경에도 불구하고 Mike는 남다른 위업을 달성했다. 그는 칭찬을 받을 만하다.",
"350. 청중은 그의 설들력 있는 강의에 감명을 받았다.",
"351. 서민 출신이지만, John은 세계적인 명성을 얻었다.",
"352. 그는 전후에 막대한 재산을 축적했다.",
"353. 그는 이전에는 유복하고 인심도 좋았는데, 지금은 그 날 그 날 생계를 유지한다.",
"354. Nick은 결코 그 보수에 만족하지 않는다. 그는 자기 중심적이며 욕심이 많다.",
"355. '전부 합해서 나한테 200달러 빌렸어, Bob. 언제 갚을 거야?' '미안해, 돈이 없어.' '또야?'",
"356. 놀랍게도 Brian의 빚은 상당한 액수에 달했다.",
"357. 과거의 영광에 집착하는 것을 그만둬라. 그렇지 않으면 뒤처지게 될 것이다.",
"358. 너는 오늘의 어려운 현실에서 도망칠 수 없으므로, 그것에 순응해야 한다.",
"359. 번영은 영원히 지속되는 것이 아니다. 다시 말해서 언젠가는 끝나는 것이다.",
"360. 그 일에는 적절한 능력이 필요하다. 컴퓨터를 쓸 줄 아는 능력은 절대 조건이다.",
"361. 이 봉투에 이력서를 넣어서 인사과에 제출해 주십시오.",
"362. 일이 잘 될 거라고 믿는 것을 보니 넌 낙관적이구나. 가능성은 기껏해야 50%뿐이야.",
"363. 등록 용지는 무료로 받으실 수 있습니다.",
"364. 이 강습회에 참가를 희망하시는 분은 지금 전화 주십시오.",
"365. 더 질문하실 것이 있으시면 주저하지 마시고 무료 전화 1-800-555-1212로 전화 주십시오.",
"366. 'Bob, 요즘 어떻게 지내?' '최고야! 취직 면접이 잘 됐어.' '축하해!'",
"367. 그는 연수생들에게 지시를 했으나, 연수생들은 그 지시가 무엇인지 전혀 몰랐다.",
"368. 한번에 두 가지를 할 수는 없어! 그건 무리야. 하나씩 해.",
"369. 'Bob, 그녀를 방해하지 마. 상관하지 말라구.' 라고 그는 작은 소리로 말했다.",
"370. 그렇게 집요하게 그녀를 귀찮게 하면 그녀가 화를 낼 거야.",
"371. 그는 너무 어린애 같아서 유혹을 이길 수 없었다.",
"372. '소동 좀 그만 부려. 정말 짜증나!' 라고 그녀는 외쳤다.",
"373. Nick에게 말대꾸해 봐야 소용없어. 말하자면 그는 ‘독재자’야.",
"374. 그들은 그의 앞에서는 매우 예의바르지만, 실제로는 언제나 뒤에서 속닥거린다.",
"375. '너는 Nick을 무시해, 그렇지?' '그렇지 않아. 난 그를 존경한다구.'",
"376. 그의 끊임없는 모욕이 그녀를 화나게 했다.",
"377. 단지 서류 정리나 하고 차나 따르는 일에 질렸어. 그만두기로 결심했어.",
"378. 실제로 많은 사람들이 수입 내에서 어떻게든 충당하느라 고생한다. 매월 10만엔으로 어떻게 생활할 수 있겠는가?",
"379. 여직원들이 그들의 일상적인 업무에 불평을 하는 것도 당연하다. 그 일들은 전혀 보람이 없다.",
"380. 근본적인 구조 조정 덕분에 당사의 흑자는  3배로 늘어났다.",
"381. 오늘날의 많은 사람들은 회사에 대한 충성이 어리석은 생각이라고 간주하고 있다.",
"382. 나는 먼 교외에서 통근해야만 한다. 정말 지겹다!",
"383. 나는 남은 인생을 나의 이상을 추구하며 살고 싶다.",
"384. 은퇴한 후 Teresa는 고아를 돌보는 데에 전념했다.",
"385. 어려움에 처한 아이들을 위해 우리는 모금 활동을 함께 했다.",
"386. 그 자선 단체는 약 20억 엔을 기부한 인물의 이름을 따서 이름 지어졌다.",
"387. 그의 자서전은 오늘 발매되었는데, 오전 중에 매진되었다.",
"388. 종종 고결한 인물로 일컬어지는 Ted가 시장에 입후보할 예정이다.",
"389. 그 후보자는 선거 결과에 낙담했다.",
"390. 시 의회는 구체적인 문제에 좀더 초점을 맞추어야 한다.",
"391. 연금 생활자가 어렵게 생활할 수밖에 없다는 것은 사실이다.",
"392. 이 자료는 빼야 해. 정확하지가 않아.",
"393. 우리는 정치가라고 하면 위선을 연상하는 경향이 있다.",
"394. 그들은 우리의 생활 수준을 높이는 것이 아니라 우리를 착취하는 것에 우선 관심이 있다.",
"395. 한때 그 남자는 보수당에 지배적인 영향력을 미쳤지만, 지금은 힘이 약화되고 있다.",
"396. 대변인은 '조사 중입니다.'라는 말을 하고는 일체의 언급을 거부했다.",
"397. 경찰은 배후 조종자가 있다고 말한다.",
"398. 간부들은 뭔가의 보답을 기대하며 관료들을 요정, 즉 고급 일본 음식점에서 접대했다.",
"399. 그의 비서는 어떤 기밀 정보도 누설한 적이 없다고 단호하게 부인했다.",
"400. 해고되는 것을 두려워하기 때문에 고용주의 의견을 과감히 부정하려고 하는 사람은 아무도 없다.",
"401. 그는 자신의 존엄성을 지키기 위해 유망한 직업을 희생했다.",
"402. 자신의 운명에 안주할 것이라면 자살하는 편이 낫다.",
"403. 독약을 먹고 자살하려던 바로 직전에 그는 다시 생각해 보고 자살을 하지 않기로 했다.",
"404. 그 애매한 소문은 거짓이라고 판명되었다. 그럼에도 불구하고 약간의 의심은 여전히 남아 있다.",
"405. 한 정부 고관이 기업에서 뇌물을 받았다는 혐의를 받고 있지만, 체포하기에는 증거가 불충분하다.",
"406. 그 사업의 책임자인 Jason은 부정 행위를 했다는 이유로 해고되었다.",
"407. 내가 아는 한, 그는 그 사기 음모에는 관련되어 있지 않다.",
"408. 관련 서류 더미를 조사하던 중에 그들은 진실을 찾아냈다.",
"409. 그들이 수십 년 동안 위법 거래를 은폐하고 있었던 것이 재판 중에 밝혀졌다.",
"410. 형사는 그 자리에서 그의 증언을 한 마디도 틀리지 않고 받아적었다.",
"411. 내 평생 처음으로 양심의 가책을 느꼈지만, 달리 도망칠 방법이 없었습니다.",
"412. 어젯밤에 꾼 생생한 악몽이 아직도 머리에서 떠나질 않는다.",
"413. 대체로 기자들은 주저하지 않고 개인의 사생활을 침해한다.",
"414. 그 작가는 몇 번씩이나 그의 원고를 수정했다.",
"415. 그는 타인의 과실을 지적함에 있어서는 누구에게도 뒤지지 않는다.",
"416. 대개 엘리트들은 비판에 민감한 반응을 보이지 않는다.",
"417. 한 타블로이드판 신문에 그가 마약 중독자라는 것이 밝혀지면서, 그의 평판은 거의 땅에 떨어졌다.",
"418. 그들은 그 방위 계획을 전면적으로 검토하여 많은 문제점들을 지적해냈다.",
"419. 테러에 관련된 사람이라면 누구든지 용서하지 않을 것이다.",
"420. 악명높은 반란군들은 결국 잡혀서 구치소에 가두어졌다.",
"421. 폭동을 진압하기 위해 신속하게 군대가 파견되었다.",
"422. 우리는 폭력이라는 수단을 취할 것이 아니라 이성에 호소해야만 한다.",
"423. 현재로서는 유화 전술을 취하는 것이 좋을 것 같습니다.",
"424. 군대는 전 영토를 점령하는 데에 성공하였다.",
"425. 이런 상황에서는 적이 항복하지 않을 수 없다. 그들은 더 이상 버틸 수 없다.",
"426. 조만간 인질들은 풀려날 것이다.",
"427. 전제 정치 하에서 죄없는 사람들이 시민권을 박탈당했다.",
"428. 몇몇 병사들은 마지못해 명령에 따랐다.",
"429. 그의 정권은 틀림없이 무너질 것이다.",
"430. 동맹국들은 그 침략 행위가 국제 연합의 결의에 위반되는 것이라고 엄격히 비난했다.",
"431. 그 나라에서 내란이 발발할 가능성을 배제할 수는 없다.",
"432. 그 식민지는 독립을 선언하고 공화국이 되었다.",
"433. 그 고결한 애국자에게 경의를 표하는 거대한 기념비가 세워졌다.",
"434. 그는 무릎을 꿇고 고인의 넔을 위해 기도했다.",
"435. 최고 재판소는 황궁 가까이에 위치하고 있다.",
"436. 낙태 합법화에 찬성하는 단체가 낙태 금지에 대해 항의했다.",
"437. Ford 상원 의원은 그 격렬한 논쟁에서 중립적 입장을 고수했다.",
"438. Ford씨는 일  주일 내내 곤란한 입장에 처해 있었다. 그는 더 이상 그것에 대처할 능력이 없다.",
"439. 수뇌 회담은 전세계에서 동시에 방송될 예정이다.",
"440. 외교적 대화 덕분에 그 분쟁에 종지부를 찍을 수 있었다.",
"441. 양국의 상호 이해를 키워가기 위해 Johnson 씨가 친선 대사로 임명되었다.",
"442. 그 전문가는 국제적인 긴장감이 점차적으로 고조될 것이라고 예측하고 있다.",
"443. 내 생각에 영구적인 평화는 단지 환상일 뿐이다.",
"444. 소수 민족들은 편견, 빈곤, 억압과 싸우고 있다.",
"445. 모든 차별을 없애기 위해 우리는 온갖 노력을 해야만 한다.",
"446. 이민 온 사람들은 육체적, 정신적 고통을 참아 왔다.",
"447. 그 개정안은 인종의 다양성을 고려하지 않았다는 이유로 각하되었다.",
"448. 말할 것도 없이, 난민들은 자유를 간절히 원하고 있었다.",
"449. 한 조사에 따르면, 요즘은 다섯 명 중 세명이 외교 문제에는 무관심하다고 한다.",
"450. 안전 보장  조약이 기한 만료가 되면 한국과 미국의 관계는 어떻게 될 것인가?",
"451. 일본이 불공평한 관세를 철폐하지 않으면 미국은 제재 조치를 취할 것이다.",
"452. 지금이라도 양국 간에는 무역 마찰이 생길 수 있다.",
"453. 우리에게 있어서 최우선 사항은 이 논쟁을 최종적으로 해결하는 것이다. 그러기 위해서 상대측과의 타협도 각오하고 있다.",
"454. 연방 정부의 예산안은 가까스로 의회의 승인을 얻었다.",
"455. 그는 정부가 다른 세입원을 찾아야 한다고 주장하고 있다.",
"456. 여론 조사의 결과에 따르면, 압도적인 대다수의 사람들이 그 법률을 지지하고 있다.",
"457. 경찰은 그 잔혹한 살인 사건의 실마리를 찾고 있다.",
"458. 그 남자는 제정신이 아님에 틀림없다. 선악을 구별하지 못한다.",
"459. 흉기에 남겨진 지문이 용의자의 지문과 일치한다.",
"460. 그 저명한 심리학자가 유괴죄로 고소당한 것에 우리는 너무 놀랐다.",
"461. 배심단에 의한 유죄 평결이 대논쟁을 불러 일으켰다.",
"462. 그 남자는 정상참작을 간청했지만, 그의 죄에 대해 20년의 징역형이 언도되었다.",
"463. 근무 중인 경관은 한 노인이 자신의 뒤에서 다가오고 있는 것을 알아차렸다.",
"464. 그는 그 집에 침입하려는 도둑을 발견했다.",
"465. 그저께 그는 들판에서 기묘한 사건을 목격했다.",
"466. 통로 맞은편에서 누군가가 나를 물끄러미 쳐다보고 있다는 것을 알아 차리고는 돌아보았다. 그러나 아무도 보이지 않았다.",
"467. 누군가가 그녀의 팔을 잡았을 때, 그녀는 놀라서 비명을 질렀다.",
"468. 그녀가 무사하다는 소식을 듣고서, 그는 안도의 한숨을 쉬었다.",
"469. 총알이 그의 가슴을 관통하여 그는 위독한 상태에 빠졌다.",
"470. 현재로서는, 그렇게 된 것이 고의적인 것인지 과실인지 아직 확실하지 않다.",
"471. 한 식품 매장이 화재로 전소하여 잿더미가 되었다.",
"472. 폭발물 저장 창고가 갑자기 폭발하여 엄청난 불길을 진화하는데 이틀이 걸렸다.",
"473. 30층짜리 빌딩에서 폭탄이 폭발하여 50명 이상의 사람들이 중상을 입었다.",
"474. 아테네로 향하던 화물선 한 척이 지중해에서 흔적도 없이 침몰했다.",
"475. 무모한 사람들이 남극 탐험 중 동사했다.",
"476. 같은 일이 반복되지 않도록 그 비극을 기억해 두어야 한다.",
"477. 그 전시회는 고대 문명에 대한 깊은 이해를 제공한다.",
"478. Giotto는 이탈리아 르네상스의 계기를 마련한 사람으로 평가된다.",
"479. Bob은 장식된 액자에 그 초상화를 넣었는데, 위아래가 거꾸로 되었다.",
"480. 이 장엄한 대성당의 기원은 중세까지 거슬러 올라간다.",
"481. 그는 아시아의 종교에서 영감을 얻어 여러 개의 멋진 조각 작품들을 만들어 냈다.",
"482. 그들은 매장된 보물을 찾기 위해 사막을 탐험했다.",
"483. 그 대부호는 아무리 돈이 많이 들더라도 그 걸작을 손에 넣겠다고 주장했다.",
"484. 신화나 전설은 대대로 이어서 전해져야 한다.",
"485. 그 언어학자는 몇 가지의 중국어 방언을 유창하게 말한다.",
"486. 그 부족은 그들의 선조를 숭배하며, 우리들에게는 친숙하지 않은 독자적인 언어를 말한다.",
"487. 그 주에서는 아직 오랜 관습이 널리 행해지고 있다고 그 문화 인류학자는 말한다.",
"488. 사악한 마녀는 그 남자에게 나쁜 마법을 걸어 벌레로 변하게 했다.",
"489. 그들은 그 가파른 오솔길을 따라 전진했다. 그것은 국경에 도달하는 유일한 방법이었다.",
"490. 동굴에서 큰 원숭이가 나타나자 그들은 놀라서 달아나 버렸다.",
"491. '믿지 않을지 모르겠지만, 우주인을 봤어. 그리고 사라져 버렸다구!' '농담 그만해!'",
"492. 상당히 많은 사람들이 그 부부의 기념일을 축하하기 위해 초대되었다.",
"493. 이제 곧 준비 완료입니다. 그동안 가볍게 음식을 드시고 계십시오.",
"494. 그녀는 현란하고 특이한 옷을 입고 있었기 때문에 인파 속에서도 눈에 띄었다.",
"495. 손님들은 모두 그녀의 대접에 감동을 받았다.",
"496. 그녀의 초라한 옷은 그 행사에 어울리지 않았다.",
"497. 그 화제는 우연히 알게 된 사람들과 이야기하기에는 너무 사적이다.",
"498. Tom은 취하면 품위가 없어지고 사람들에게 불쾌감을 준다. 그를 가까이하지 말아라.",
"499. 그는 그녀가 암시하는 것을 거의 이해할 수 없었다.",
"500. Bob은 몇몇 소녀들 앞에서 놀림을 당하자 어쩔 줄 몰라했다.",
"501. 그의 애매한 대답은 그녀를 더욱 짜증나게 했다.",
"502. Bob은 매우 소심해서 여자들과 이야기를 하면 얼굴이 붉어진다.",
"503. Nick은 지방 출신자라면 누구든지 무시한다.",
"504. '무슨 일이야, Bob? 얼굴이 안 좋아 보인다.'",
"505. Bob은 변장을 하고 있었지만, 나는 한눈에 그를 알아보았다.",
"506. '왜 킬킬거리며 웃는 거야?' 'Bob, 땀복을 거꾸로 입었잖아!' '앗!'",
"507. 그는 사람들과 친해지는데 서툴러서 항상 외톨이다.",
"508. 그는 자신이 받아들여질 곳을 찾지 못해서, 극도의 불안과 고독에 빠져 있었다.",
"509. 나는 새로운 환경에 익숙해지는 것이 꽤 어렵다는 것을 알게 되었다.",
"510. 나는 저렇게 세련된 사람들 속에 있는 것이 전혀 어울리지 않는다고 느꼈다.",
"511. 솔직히 말해서, 나는 클래식 음악을 좋아하지 않는다. 반면에 Molly는 그것에 완전히 빠져 있다.",
"512. Bob은 곤충을 관찰하는 것에 재미를 느끼고 있다.",
"513. '기분 전환으로 트럼프나 그런 거 안 할래?' '미안하지만, 그럴 기분이 아니야.'",
"514. '먼저 하세요.' '아니에요, 먼저 하세요.' '감사합니다.' '천만에요.'",
"515. 그의 조카딸은 나이에 비해서 사교적이고 어른스럽다. 20대라고 해도 통할 것이다.",
"516. '건강 조심하고, 가족 모두에게 안부 전해 줘.' '그럴게. 또 보자.'",
"517. 답장을 기다리고 있겠습니다. 경의를 담아. (편지에서)",
"518. 시간 좀 내 주실 수 있으세요? 우리 두 사람에게 중요한 일에 대해 이야기하고 싶습니다.",
"519. 당신에게는 사소한 것으로 생각될지 모르지만, 저에게 있어서 그것은 주의를 기울일 만한 가치가 있는 것입니다.",
"520. Bob에 대해서 말하자면, 그는 어떤 일이든 받아들이는 타입이다. 대조적으로 Jane은 매우 신중하다.",
"521. 어색한 침묵 끝에 Bill은 그녀의 손을 잡고 위층으로 끌고 올라갔다.",
"522. Bill은 단지 Monica를 위로하고 싶었을 뿐이었는데, 그녀는 그것을 그가 자신에게 마음이 있는 것으로 해석했다.",
"523. 그는 그녀가 깊이 잠든 것을 확인하고, 몰래 방을 빠져 나와 여행을 떠났다.",
"524. Lisa, 비밀인데, 우연히 Nick이 어떤 여자를 정열적으로 포옹하고 있는 것을 봤어.",
"525. 그런 발언은 오해를 받기 쉽다.",
"526. '더 이상 그것을 참을 수가 없어!' '진정해. 내가 지금 그 곳으로 갈게.' (전화에서)",
"527. 그것을 그대로 받아들이지 마. 그는 과장되게 말하는 경향이 있거든.",
"528. 'Lisa를 바보 취급한 것에 대해 사과해야 해. 이번엔 너무했어.' '그래, 그렇게 할게. 조만간 그녀의 기분이 좋아지면.'",
"529. 'Lisa, Nick과는 잘 지내지?' '때때로 그 와의 이혼을 생각하기도 해.' '농담이겠지!'",
"530. 그녀는 울면서 그의 편지를 마구 찢어버렸다.",
"531. 'Jennifer가 나를 속였어!' '그녀를 신용하지 않을 정도의 분별력이 있어야 했는데.'",
"532. Tom은 자신의 인생 중 많은 시간을 낭비했던 것을 후회했다.",
"533. 나는 사춘기 시절을 되돌아볼 때마다 항상 우울해진다.",
"534. 'Jennifer가 나를 버리고 다른 남자에게 가 버렸어.' '이런, 심란하겠구나.' '그렇지도 않아. 난 그런 것에 익숙한 걸.'",
"535. '그녀가 그를 전송하러 오지 않은 것은 당연해.' '왜?' '둘이 헤어졌잖아.' '이런, 유감이군!'",
"536. '여기서 나 혼자 살아간다는 것은 고문이야.' 라고 그는 흐느껴 울며 말했다.",
"537. '솔직히 말하면 나 Ken에게 빠졌어. 그는 용감하고, 자신감도 있고, 게다가 위험을 무릅쓰는 것도 결코 두려워하지 않거든.' '나라면 그에게 데이트 신청할 거야.'",
"538. '나는 Jennifer와 사귀다가 헤어지기를 오랫동안 반복해 왔어.' '넌 변함없이 우유부단하구나. 이제 슬슬 정착할 때가 아니니?'",
"539. 'Jennifer에게 계속 속고 있었다는 걸 알게 되었어.' '정말 순진하구나! 그녀의 본성을 간파하지 못했었어?'",
"540. 사실 그녀는 누군가와 사귀고 있지만, 나는 그녀를 포기하지 않겠다.",
"541. '안녕, jane. 무슨 별일 있니?' '새로운 일은 없어. 너는?' '난 Jennifer와 결혼했어.' '와! 축하해!'",
"542. 어려움에 처하거나 우울할 때는 언제든지 내가 네옆에 있을게.",
"543. '기쁨'은 '슬픔'의 반대입니다.",
"544. 'Jannifer는 나를 바보라고까지 불러 놓고도 그 말을 취소하지 않아.' ' 자업자득이야! 네가 그녀를 화나게 했지, 그렇지?'",
"545. '왜 그녀의 오만함을 참아 주는 거야? 그녀는 널 이용하고 있을 뿐이야.' '닥쳐!'",
"546. 서두르지 마. 그것을 깊이 생각하는데 2, 3일은 필요할 테니까.",
"547. Bob은 자신의 힘으로 이 어려운 시련을 극복해야만 한다.",
"548. 파리와 모기가 그의 명상을 방해했다.",
"549. 두 번의 연기 끝에 그 신성한 의식이 행해졌다.",
"550. 스님이 갑자기 웃음을 터뜨려 엄숙한 분위기를 망쳤다.",
"551. 기침이나 재채기 또는 하품을 할 때에는 손으로 입을 가리세요.",
"552. '그녀의 친척 중 한 사람이 3일 전에 죽었어.' '저런, 그것 참 안됐네. 가엾어라.'",
"553. 그녀는 장례식에 참석해야 할 뿐만 아니라, 모든 일을 마무리해야 한다.",
"554. 'Jane, 네 기분을 이해해. 슬픔이 금방 사라지지는 않을 거야.' '괜찮아. 극복할게.'",
"555. 그녀는 유년 시절의 소중한 추억을 간직하고 있다.",
"556. 'Jennifer라고 하면, 그녀는 어느 실업가와 약혼했어.' '기가 막혀 말도 안 나오는군. 파탄이나 나지 않길 바래야겠군.'",
"557. 요즘은 결혼의 동기가 반드시 순수한 것은 아니다. 예를 들어 Jennifer를 봐라.",
"558. Bob에게 친절하게 대해 줘. 알다시피, 최근 그에게 계속 힘든 일이 이어지고 있잖아.",
"559. '그런데, 지금 몇 시야?' '음, 8시 15분 전이야.'",
"560. 'Bob, 오늘은 여기까지 해 두자. 배고파 죽겠어.' '그러자. 저녁은 내가 살게.'",
);

echo ("<html>
		<head>
		<meta http-equiv='content-type' content='text/html; charset=euc-kr'/>
		<title>듀오 3.0</title>
		<style>
		Body {scrollbar-face-color: #FFFFFF; scrollbar-shadow-color: 999798;
				  scrollbar-highlight-color: 999798; scrollbar-3dlight-color: #FFFFFF;
				  scrollbar-darkshadow-color: #F6F6F6; scrollbar-track-color: #FFFFFF;
				  scrollbar-arrow-color: 999798;}
		</style>
</head>");

echo ("<body bgcolor=white text=black link=black vlink=black alink=black leftmargin=10 marginwidth=10 topmargin=10 marginheight=10>

<style>
.fontLine{font-size:30px;color:black}
</style>

<TABLE align='left' valign='top' width=100% border=0><TR align='left' valign='top'><TD>

<table align='left' valign='top' border='0' cellpadding='0' cellspacing='0'>
	<tr align='left' valign='top'>
		<td>");
if ($show == 1)
{
	for ($i = $number; $i < $number+$size; $i++)
	{
		echo ("<b>$duoEnglish[$i]</b><br>$duoKorean[$i]<br>&nbsp;<br>");
	}
}
else
{
	for ($i = $number; $i < $number+$size; $i++)
	{
		echo ("<b>$duoEnglish[$i]</b><br><span class=fontLine>&nbsp;</span><br>");
	}
}
echo ("<table width=290 border=0 align=left><tr><td>
			<form name='english' action='english_duo30.php' method='post'>
			<font color=green> <b>Number</b> </font><input type='text' name='number' size=3 maxlength=3>
			<font color=orange> <b>List</b> </font><input type='text' name='size' size=3 maxlength=3>
			<input type='submit' value='OK'>
				<SCRIPT>
				document.english.number.focus();
				</SCRIPT>
			</form>
</td><td align=left>
			<form name='korean' action='english_duo30.php' method='post'>
			<input type='hidden' name='number' value=$number>
			<input type='hidden' name='size' value=$size>
			<input type='hidden' name='show' value=1>
			<input type='submit' value='한국어'>
			</form>
</td></tr></table>

</td></tr><tr><td>총 560개의 문장이 있습니다. 'Number'는 원하는 문장 번호를 'List'는 원하는 갯수를 의미합니다.</td></tr></table>

</TD>
</TR>
</TABLE>

</body>
</html>");

?>
